# Install of Libraries

In [1]:
# Install required libraries

!pip install -q pandas numpy sentence-transformers faiss-cpu transformers accelerate torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.8/18.8 MB 89.9 MB/s eta 0:00:00

In [24]:
!pip install -q google-genai

# Necessary Libraries

In [34]:
import pandas as pd
import numpy as np
import torch
import faiss
import time
from google.genai.errors import ServerError

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("PyTorch:", torch.__version__)
print("CUDA Available:", torch.cuda.is_available())

Pandas: 2.2.3
NumPy: 2.1.3
PyTorch: 2.11.0+cu130
CUDA Available: True

# Dataset Loading

In [3]:
df = pd.read_csv("case_files_total.csv")

print("Dataset Shape:", df.shape)
df.head(6)

Dataset Shape: (53446, 10)

,Unnamed: 0,name,case_category,case_type,case_info,judgement,tokens,sentences,label,proof_sentence
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,74634371.txt,civil,writ petition,reportable in the supreme court of india civil...,thus spake benjamin franklin in his letter of ...,9974.0,254.0,Accepted,"34. we are, therefore, of the view that this a..."
2,2,746230.txt,civil,writ petition,case number appeal civil 588 of 1972 petitio...,difficult to share the view taken by the high...,1411.0,56.0,Accepted,"6. accordingly, we allow the appeal with costs."
3,3,746330.txt,civil,writ petition,petitioner western india plywood limited vs. r...,j u d g m e n t the following judgement of the...,2616.0,85.0,Accepted,for the aforesaid reasons this appeal is allowed.
4,4,746327.txt,civil,writ petition,"petitioner asstt.\ncustodian, e.p. ors.\nvs. r...",custodian first stated that the property was n...,2763.0,95.0,Accepted,appeal allowed.
5,5,746119.txt,criminal,special leave petition,"judgment c.a. vaidialingam, j. 1.\n",this appeal by special leave is against the ju...,2571.0,106.0,Rejected,15. in the result the appeal fails and is dism...

In [4]:
print("Rows:", len(df))
print("Columns:")

for col in df.columns:
    print("-", col)

Rows: 53446
Columns:
- Unnamed: 0
- name
- case_category
- case_type
- case_info
- judgement
- tokens
- sentences
- label
- proof_sentence

# Data Preprocessing

In [5]:
# Checking missing values
df.isnull().sum()

Unnamed: 0           0
name                 1
case_category     9834
case_type          736
case_info           25
judgement         3302
tokens               2
sentences            2
label                2
proof_sentence       2
dtype: int64

In [6]:

# HANDLE MISSING VALUES

# Numerical columns → Median
numeric_columns = df.select_dtypes(
    include=[np.number]
).columns

for col in numeric_columns:
    if df[col].isnull().sum() > 0:
        median_value = df[col].median()
        df[col] = df[col].fillna(median_value)

        print(
            f"{col}: Missing values replaced with median = {median_value}"
        )


# Text / categorical columns → Mode
text_columns = df.select_dtypes(
    include=["object", "string", "category"]
).columns

for col in text_columns:
    if df[col].isnull().sum() > 0:

        # Most frequently occurring value
        mode_value = df[col].mode()[0]

        df[col] = df[col].fillna(mode_value)

        print(
            f"{col}: Missing values replaced with mode = {mode_value}"
        )


# Check remaining missing values
print("\nRemaining Missing Values:")
print(df.isnull().sum())

tokens: Missing values replaced with median = 2400.0
sentences: Missing values replaced with median = 76.0
name: Missing values replaced with mode = 1077544.txt
case_category: Missing values replaced with mode = civil
case_type: Missing values replaced with mode = appeal
case_info: Missing values replaced with mode = order 1.

judgement: Missing values replaced with mode = respondents judgment dr. arijit pasayat, j. 1. challenge in this appeal is to the judgment passed by the appellate tribunal for electricity, new delhi  hereinafter referred to as to the tribunal .
the appeal has been filed under section 125 of the electricity act, 2003  in short the act .
2. the primary stand of the appellant is that though the tribunal accepted that electricity regulatory commissions  in short the regulatory commission  did not have any power to determine tariff for trading, it invoked sections 60 and 66 of the act to direct all regulatory commissions to fix trading margins as if it involved tariff determination.
stand of the appellant is that only appropriate regulatory commission can invoke provisions of section 60 upon arriving at a finding that a particular licensee or generator had conducted himself in the specified manner which has an adverse effect on competition in the electricity industry.
according to the appellant the tribunal issued directions on assumptions and presumptions without any adjudication on tests laid down in section 60 of the act.
in essence, the stand is that the tribunal is not empowered to determine tariff in exercise of its revisional supervisory powers under section 121 of the act.
it was pointed out that the exercise of power under section 121 of the act was not permissible because respondent number1-gajendra haldea had neither initiated any proceedings before the concerned regulatory commission and had also not made any grievance relating to excessive exercise or non exercise of jurisdiction by such regulatory commission.
strong reliance is placed on a decision of this court in grid corporation of orissa limited v. gajendra haldea and ors.   2008  11  scale 313  holding that respondent-gajendra haldea cannot be treated as a person aggrieved under the act.
3. respondent number1 on the other hand supported the judgment and submitted that grid corporations case  supra  has no application to the facts of the case.
4. in order to appreciate the rival submissions section 111 needs to be noted.
the same reads as follows 111.
appeal to appellate tribunal.- 1  any person aggrieved by an order made by an adjudicating officer under this act  except under section 127  or an order made by the appropriate commission under this act may prefer an appeal to the appellate tribunal for electricity provided that any person appealing against the order of the adjudicating officer levying any penalty shall, while filing the appeal, deposit the amount of such penalty provided further that where in any particular case, the appellate tribunal is of the opinion that the deposit of such penalty would cause undue hardship to such person, it may dispense with such deposit subject to such conditions as it may deem fit to impose so as to safeguard the realisation of penalty.   2  every appeal under sub-section  1  shall be filed within a period of forty five days from the date on which a copy of the order made by the adjudicating officer or the appropriate commission is received by the aggrieved person and it shall be in such form, verified in such manner and be accompanied by such fee as may be prescribed provided that the appellate tribunal may entertain an appeal after the expiry of the said period of forty-five days if it is satisfied that there was sufficient cause for not filing it within that period.   3  on receipt of an appeal under sub-section  1 , the appellate tribunal may, after giving the parties to the appeal an opportunity of being heard, pass such orders thereon as it thinks fit, confirming, modifying or setting aside the order appealed against.   4  the appellate tribunal shall send a copy of every order made by it to the parties to the appeal and to the concerned adjudicating officer or the appropriate commission, as the case may be.   5  the appeal filed before the appellate tribunal under sub- section  1  shall be dealt with by it as expeditiously as possible and endeavour shall be made by it to dispose of the appeal finally within one hundred and eighty days from the date of receipt of the appeal provided that where any appeal could not be disposed of within the said period of one hundred and eighty days, the appellate tribunal shall record its reasons in writing for not disposing of the appeal within the said period.   6  the appellate tribunal may, for the purpose of examining the legality, propriety or correctness of appropriate commission under this act, as the case may be, in relation to any proceeding, on its own motion or otherwise, call for the records of such proceedings and make such order in the case as it thinks fit.
5. in grid corporations case  supra  it was inter-alia observed as follows 15.
it is unnecessary to go into the question as to the nature of the transaction, because respondent number1-gajendra haldea in order to prove that he had locus standi relied on sections 121 and 142 of the act.
it was also stated that it is not in the nature of pil.
it was stated that the prayer for refund was not being pressed.
16.
a bare reading of sections 121 and 142 of the act which read as follows shows that those provisions are not applicable.
121.
power of appellate tribunal- the appellate tribunal may, after hearing the appropriate commission or other interested party, if any, from time to time, issue such orders, instructions or directions as it may deem fit, to any appropriate commission for the performance of its statutory function under this act.
142. punishment for non-compliance of directions by appropriate commission.-in case any complaint is filed before the appropriate commission by any person or if that commission is satisfied that any person has contravened any of the provisions of this act or the rules or regulations made thereunder, or any direction issued by the commission, the appropriate commission may after giving such person an opportunity of being heard in the matter, by order in writing, direct that, without prejudice to any other penalty to which he may be liable under this act, such person shall pay, by way of penalty, which shall not exceed one lakh rupees for each contravention and in case of a continuing failure with an additional penalty which may extend to six thousand rupees for every day during which the failure continues after contravention of the first such direction.
17.
therefore, the appellate tribunal was wrong in interfering with the conclusions of cerc that respondent number1s petition was not entertainable and or maintainable.
6. the order passed by the tribunal cannot be maintained in view of what is stated in grid corporations case  supra  and is set aside.
the appeal is allowed without any order as to costs.
j.  dr. arijit pasayat  j.  asok kumar ganguly  new delhi, april 09, 2009
label: Missing values replaced with mode = Rejected
proof_sentence: Missing values replaced with mode = appeal dismissed.

Remaining Missing Values:
Unnamed: 0        0
name              0
case_category     0
case_type         0
case_info         0
judgement         0
tokens            0
sentences         0
label             0
proof_sentence    0
dtype: int64

# Preparing dataset for RAG

In [7]:
# Keep only rows having judgment text

df = df.dropna(subset=["judgement"])

# Remove duplicate judgments

df = df.drop_duplicates(subset=["judgement"])

print("Dataset after cleaning:", df.shape)

Dataset after cleaning: (41007, 10)

In [8]:
df["text_length"] = df["judgement"].astype(str).str.len()

print(df["text_length"].describe())

count    41007.000000
mean     15682.937377
std      10733.611932
min          1.000000
25%       6237.000000
50%      13444.000000
75%      24822.500000
max      32765.000000
Name: text_length, dtype: float64

In [9]:
RAG_DOCS = 10000

rag_df = df.sample(
    n=min(RAG_DOCS, len(df)),
    random_state=42
).reset_index(drop=True)

print("RAG Documents:", len(rag_df))

RAG Documents: 10000

In [10]:
# Create Document Text
def create_document(row):

    return f"""
Case Category: {row.get('case_category', 'Unknown')}

Case Type: {row.get('case_type', 'Unknown')}

Case Information:
{row.get('case_info', 'Unknown')}

Judgment:
{row['judgement']}
""".strip()


rag_df["document"] = rag_df.apply(create_document, axis=1)

print(rag_df["document"].iloc[0][:3000])

Case Category: civil

Case Type: writ petition

Case Information:
petitioner h. a. k. rao, chartered accountant vs. respondent council of institute of chartered accountants of india, new date of judgment 13/12/1966 bench rao, k. subba  cj  bench rao, k. subba  cj  shah, j.c. sikri, s.m. ramaswami, v. vaidyialingam, c.a. citation 1967 air 1257 1967 scr  2  256 act chartered accountants act 1949--clause  ii , part ii, second schedule--councils power to specify any act or omission other than those covered by act or regulations as professional misconduct--scope of.
headnote the council of the institute of chartered accountants, by a notification issued on february 22, 1964, in exercise of powers conferred by cl.
ii  of part 11 of the second schedule to the chartered accountants act, 1949, notified, inter alia, that a member of the institute shall be deemed to be guilty of misconduct if, in connection with elections to the councils of the lnstitute.,
he took part directly or indirectly in  1  issuing manifestoes or circulars  2  canvassing votes by visiting places of business or residence of the voters or in any other manner.
the appellant, who was a prospective candidate for election to the central council of the institute, filed a writ petition to quash the notification.
it was contended on his behalf that the power of the council to issue a notification is limited by the express provisions of cl.
ii  of part ii of the second schedule to the act.
under cl.
i  any contravention of the provisions of the act or of the regulations made thereunder was professional misconduct therefore the expression other act or omission in cl.
ii  must be an act or omission other than those covered by the act or the regulations.
under cl.  2  of regulation 54-a, undue influence by interfering with the free exercise of any electoral rights was misconduct, but the proviso to cl.
2  which permitted a declaration of policy or a promise of a particular action saved the issuing of manifestoes and circulars from the operation of the substantive part of the clause.
the appellant therefore claimed that he had a legal right to issue circulars or manifestoes within the meaning of the proviso and that the impugned notification being in derogation of the regulation, was illegal.
it was further contended that the notification was inconsistent with cl.
4b  of regulation 54a, because that clause only prohibited canvassing for votes within a distance of 200 meters from the polling booths, thereby impiedly permitting canvassing beyond that distance cf.  4b  detracted only to a limited extent from the legal right to canvass and the impugned notification containing a prohibition against general canvassing beyond these limits contravened both cl.
2  and cl.  4b  of regulation 54-a and was therefore bad.
the high court held that the impugned notification in so far as it directed that the issuing of manifestoes or circulars was misconduct, was illegal but that the rest of it was

In [11]:
# Text Chunking
def chunk_text(text, chunk_size=700, overlap=100):

    words = text.split()

    chunks = []

    start = 0

    while start < len(words):

        end = start + chunk_size

        chunk = " ".join(words[start:end])

        if chunk.strip():
            chunks.append(chunk)

        start += chunk_size - overlap

    return chunks

In [12]:
sample_chunks = chunk_text(rag_df["document"].iloc[0])

print("Number of chunks:", len(sample_chunks))

print("\nFirst chunk:\n")
print(sample_chunks[0][:2000])

Number of chunks: 7

First chunk:

Case Category: civil Case Type: writ petition Case Information: petitioner h. a. k. rao, chartered accountant vs. respondent council of institute of chartered accountants of india, new date of judgment 13/12/1966 bench rao, k. subba cj bench rao, k. subba cj shah, j.c. sikri, s.m. ramaswami, v. vaidyialingam, c.a. citation 1967 air 1257 1967 scr 2 256 act chartered accountants act 1949--clause ii , part ii, second schedule--councils power to specify any act or omission other than those covered by act or regulations as professional misconduct--scope of. headnote the council of the institute of chartered accountants, by a notification issued on february 22, 1964, in exercise of powers conferred by cl. ii of part 11 of the second schedule to the chartered accountants act, 1949, notified, inter alia, that a member of the institute shall be deemed to be guilty of misconduct if, in connection with elections to the councils of the lnstitute., he took part directly or indirectly in 1 issuing manifestoes or circulars 2 canvassing votes by visiting places of business or residence of the voters or in any other manner. the appellant, who was a prospective candidate for election to the central council of the institute, filed a writ petition to quash the notification. it was contended on his behalf that the power of the council to issue a notification is limited by the express provisions of cl. ii of part ii of the second schedule to the act. under cl. i any contravention of the provisions of the act or of the regulations made thereunder was professional misconduct therefore the expression other act or omission in cl. ii must be an act or omission other than those covered by the act or the regulations. under cl. 2 of regulation 54-a, undue influence by interfering with the free exercise of any electoral rights was misconduct, but the proviso to cl. 2 which permitted a declaration of policy or a promise of a particular action saved the issuing of manifestoes and circulars from the

In [13]:
# Create Chunk Database
documents = []

for idx, row in rag_df.iterrows():

    chunks = chunk_text(row["document"])

    for chunk_id, chunk in enumerate(chunks):

        documents.append({
            "case_id": idx,
            "chunk_id": chunk_id,
            "case_category": row.get("case_category", "Unknown"),
            "case_type": row.get("case_type", "Unknown"),
            "case_info": row.get("case_info", "Unknown"),
            "text": chunk
        })

print("Total chunks:", len(documents))

Total chunks: 53761

In [14]:
chunks_df = pd.DataFrame(documents)

chunks_df.head(6)

,case_id,chunk_id,case_category,case_type,case_info,text
0,0,0,civil,writ petition,"petitioner h. a. k. rao, chartered accountant ...",Case Category: civil Case Type: writ petition ...
1,0,1,civil,writ petition,"petitioner h. a. k. rao, chartered accountant ...",or the regulations. 263 f while the regulation...
2,0,2,civil,writ petition,"petitioner h. a. k. rao, chartered accountant ...","or through any other person, in any of the fol..."
3,0,3,civil,writ petition,"petitioner h. a. k. rao, chartered accountant ...",carrying out the objects of the act. the centr...
4,0,4,civil,writ petition,"petitioner h. a. k. rao, chartered accountant ...",of a candidate within a distance of 200 meters...
5,0,5,civil,writ petition,"petitioner h. a. k. rao, chartered accountant ...",conflict with the same. the further argument w...

# Load Embedding Model

In [15]:
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

print("Embedding model loaded.")
device = "cuda" if torch.cuda.is_available() else "cpu"

embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2",
    device=device
)

print("Device:", device)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Embedding model loaded.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Device: cuda

In [16]:
# Generate Embeddings
texts = chunks_df["text"].tolist()

embeddings = embedding_model.encode(
    texts,
    batch_size=64,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True
)

print("Embedding shape:", embeddings.shape)

Batches:   0%|          | 0/841 [00:00<?, ?it/s]

Embedding shape: (53761, 384)

In [17]:
# Create FAISS Vector Database
dimension = embeddings.shape[1]

index = faiss.IndexFlatIP(dimension)

index.add(embeddings.astype("float32"))

print("FAISS index created.")
print("Total vectors:", index.ntotal)

FAISS index created.
Total vectors: 53761

In [18]:
# Save FAISS Index
faiss.write_index(
    index,
    "legal_judgment_faiss.index"
)

print("FAISS index saved.")

# Save chunk metadata
chunks_df.to_pickle(
    "legal_judgment_chunks.pkl"
)

print("Chunk metadata saved.")

FAISS index saved.
Chunk metadata saved.

In [19]:
# Build Retrieval Function
def retrieve_documents(query, top_k=5):

    # Convert query into embedding
    query_embedding = embedding_model.encode(
        [query],
        normalize_embeddings=True
    )

    # Search FAISS
    scores, indices = index.search(
        query_embedding.astype("float32"),
        top_k
    )

    results = []

    for score, idx in zip(scores[0], indices[0]):

        result = chunks_df.iloc[idx].to_dict()

        result["similarity_score"] = float(score)

        results.append(result)

    return results

In [20]:
# Test Semantic Search
query = "What was the main issue considered by the court?"

results = retrieve_documents(query, top_k=5)

for i, result in enumerate(results):

    print("=" * 80)

    print("Result:", i + 1)

    print("Similarity:",
          round(result["similarity_score"], 4))

    print("Case Type:",
          result["case_type"])

    print("\nText:")
    print(result["text"][:1500])

================================================================================
Result: 1
Similarity: 0.639
Case Type: appeal

Text:
parties. in fact, the agreement was not acted upon. the high court proceeded on an erroneous basis as if some of the issues were not pressed before the trial court and the high court. the clauses of the agreement on which the trial court and the high court placed reliance do not prove the essence of the transactions and or intention and should not have been given undue importance. some of the basic issues like issue number12 were not adjudicated by the trial court and the high court. though reference was placed on the objections filed to the application under section 145 of the cr.p.c., stand of the appellant was not taken note of. in fact, an application had been filed for taking note of the objections which unfortunately the high court treated to have become infructuous as it was listed on the day the judgment was delivered. while considering a plea that the agreement was not intended to be acted upon, veil has to be lifted by considering the evidence and the surrounding circumstances in their proper perspective. though the trial court had granted rs.500/- p.m. as damages, the high court suo motu without even any challenge thereto by the respondent raised the same to rs.1200/-p.m. the specific stand of the appellant was that the agreement was executed as a devise to protect the plaintiffs in the suit for ejectment or and that relating to fixation of standard rent in the dispute between the plaintiffs and their landlords. the high court erroneously came to hold that payments
================================================================================
Result: 2
Similarity: 0.6099
Case Type: writ petition

Text:
Case Category: civil Case Type: writ petition Case Information: petitioner a.m. Judgment: mathur vs. respondent pramod kumar gupta date of judgment22/03/1990 bench shetty, k.j. j bench shetty, k.j. j sahai, r.m. j citation 1990 air 1737 1990 scr 2 110 1990 scc 2 533 jt 1990 1 545 1990 scale 1 527 act practice and procedure judicial restraint--need for--high court judge making derogatory remarks criticising counsel, parties or witnesses--such remark not to be made unless absolutely necessary for deciding the case. headnote while allowing a writ petition, one of the judges deliv- ered the main judgment invalidating the decision of the government on the ground that it violated article 14 of the constitution. the other judge delivered a separate, but concurring opinion which contained highly disparaging re- marks attributing mala fides and underhand dealing on the part of the state government. several appeals were filed against the said decision before this court. this court allowed the appeals and observed that the strictures passed in the concurring judgment were totally unjustified and unwarranted. state of m.p. v. nandial jaiswal ors., 1987 1 scr 1. thereafter an advocate who had no connection whatsoever with the litigation filed a review petition before the high court. it was alleged that the state government committed fraud and procured the judgment from this court. the matter was listed before a division bench on 29th october 1988, and one of the judges dismissed the revie
================================================================================
Result: 3
Similarity: 0.6089
Case Type: special leave petition

Text:
high court and submitted that the defendants-respondents ought to be held to have forfeited their rights to file their written statement and adduce evidence as the defendants were duly served with the summons and were also represented by their advocate. in spite of this the defendants chose not to file written statement although several opportunities were granted and they had also not stated any reason for not filing written statement. it was further urged that even in appeal the defendants have not disputed the factum of the suit property being joint family property and, therefore, in absence of any evidence to the contrary, the high court ought not to have interfered with the judgment and decree passed by the trial court. it was submitted that the defendants had slept over the matter and committed grave latches when they failed to file written statement for which no reason at all has been assigned by the defendants and, therefore, the high court committed error by granting undue indulgence and permitting the defendants to file written statement and documents when their right to file the same stood forfeited. 10. contesting the appeal, it was urged on behalf of the defendants- respondents that the suit of the plaintiff-appellant has been decreed only on the basis of the averments in the plaint which was legally impermissible for even if the suit has been decided in the absence of written statement, the trial court ought not to have decreed the suit without cross-examination
================================================================================
Result: 4
Similarity: 0.6037
Case Type: appeal

Text:
to have interfered with the decree of the trial court. the high court dismissed it without application of the mind and ignoring the settled legal principles. the appeal is accordingly allowed. the orders of the high court and the appellate court stand set aside and that of the trial court stands confirmed number costs.
================================================================================
Result: 5
Similarity: 0.6024
Case Type: appeal

Text:
and which had become final either because no appeal was carried to this court or, if carried, the same was dismissed. this benefit would be available to no other.

In [21]:
query = "What was the final decision of the court?"

results = retrieve_documents(query, top_k=5)

for i, result in enumerate(results):

    print("=" * 80)

    print("Result:", i + 1)
    print("Similarity:", result["similarity_score"])
    print(result["text"][:1000])

================================================================================
Result: 1
Similarity: 0.6803998947143555
and which had become final either because no appeal was carried to this court or, if carried, the same was dismissed. this benefit would be available to no other.
================================================================================
Result: 2
Similarity: 0.6737040281295776
for the parties, we record that all of them at the close of the hearing of these cases conceded that the jurisdiction of this court under article 32 of the constitution cannot be invoked to challenge the validity of a final judgment order passed by this court after exhausting the remedy of review under article 137 of the constitution read with order xl rule 1 of the supreme court rules 1966. however, all the learned counsel for the parties as also the learned attorney-general who appeared as amicus curiae, on the notice of this court, adopted an unusual unanimous approach to plead that even after exhausting the remedy of review under article 137 of the constitution, an aggrieved person might be provided with an opportunity under inherent powers of this court to seek relief in cases of gross abuse of the process of the court or gross miscarriage of justice because against the order of this court the affected party cannot have recourse to any other forum. mr.shanti bhushan, the learned s
================================================================================
Result: 3
Similarity: 0.6592947244644165
of the evidence on record. the high court was, therefore, fully justified in setting aside the judgment and order of the trial court. 11. we find no merit in the appeal and the same is, accordingly, dismissed.
================================================================================
Result: 4
Similarity: 0.6431052684783936
to have interfered with the decree of the trial court. the high court dismissed it without application of the mind and ignoring the settled legal principles. the appeal is accordingly allowed. the orders of the high court and the appellate court stand set aside and that of the trial court stands confirmed number costs.
================================================================================
Result: 5
Similarity: 0.640012264251709
which stand finally concluded. it cannot be doubted that on 20th october, 1994, the date on which the constitution bench delivered its judgment, the matters relating to compensation in the present case had not achieved the finality and had not stood finally concluded inasmuch as the same were pending in appeal in the high court and appeal is a continuation of original proceedings. so far as the award given by the collector is concerned, that can be said to have become final before the date of decision of constitution bench but not the award given by the civil court on reference. the high court, in its impugned judgment, formed an opinion that the law laid down by the constitution bench governed the cases at hand and, therefore, the award given by the civil court on reference, stood vitiated for want of notice to k.w.a. the high court allowed all the appeals pending before it and remanded the case for decision afresh by the reference court, after affording the parties an opportunity of

In [22]:
# RAG Context
def build_context(results):

    context_parts = []

    for i, result in enumerate(results):

        context_parts.append(
            f"""
SOURCE {i+1}

Case Category:
{result['case_category']}

Case Type:
{result['case_type']}

Case Information:
{result['case_info']}

Relevant Judgment:
{result['text']}
"""
        )

    return "\n".join(context_parts)

In [23]:
results = retrieve_documents(
    "What was the main issue in this case?",
    top_k=3
)

context = build_context(results)

print(context[:5000])

SOURCE 1

Case Category:
civil

Case Type:
election petition

Case Information:

supreme court of india
harmohinder singh pradhan vs ranjeet singh talwandi ors on 28 april, 2005author r lahoti
bench cji r.c. lahoti, g.p. mathur, p.k. balasubramanyan
case number
appeal  civil  8315 of 2003

petitioner
harmohinder singh pradhan

respondent
ranjeet singh talwandi ors

date of judgment 28/04/2005

bench
cji r.c. lahoti, g.p. mathur p.k. balasubramanyan

judgment
j u
d g m e n t

r.c. lahoti, cji

this appeal under section 116a of the representation of


Relevant Judgment:
cause of action under clause a of rule 11 of order vii of the code. no fault can be found with the view taken by the learned designated election judge of the high court. the appeal is devoid of any merit and is dismissed with costs.


SOURCE 2

Case Category:
civil

Case Type:
writ petition

Case Information:
reportable in the supreme court of india civilappellate jurisdiction civil appeal number 6905 of 2005 m s. s.k.l.


Relevant Judgment:
was not issued under section 30 and 31 of the act, but instead was a product of a policy decision of the government of india which aimed to augment the earnings of the respondent-railways by leasing the fslr and vp in different trains. the respondent-railways are run as a commercial undertaking, and its administration cannot be prevented from taking steps to increase its revenue, as long as they are not detrimental to the interest of the general public. it was held that the action of inviting tenders could not be quashed as being opposed to section 30 and 31. the high court observed that to prove that section 70 had been violated, the appellant had to establish that undue preference had been given to one over another, and as the appellant failed to provide any cogent evidence to that effect, this contention was dismissed. the apprehension of the appellant was that due to the leasing out of space to a third party, there was less than adequate space for the general public, and that, as a result they would have no choice but to approach the third party and pay any rate that he may quote. the high court observed that this apprehension of the appellant had been allayed by the affidavit filed by the respondents wherein they had stated that if the need arises they would ordain more space for the parcel service. thus, the high court allowed the appeals. however, with the intention of safeguarding the interest of the general public, it also issued directions to the respondent to incorporate certain regulatory checks on the unbridled power of the lessee. the checks were meant to be in the form of an upper limit on the tariff that could be charged by the contractors for different trains. aggrieved by the decision of the high court, the appellant has filed the present appeal. 9 the arguments of the learned counsel for the appellant are fourfold. firstly, babu verghese v. bar council of kerala, 1999 3 scc 422 reiterates that if the manner of taking a particular action is prescribed under a statute, that action must be undertaken and performed in that manner or not at all as there is no provision under the statute to lease out space to a third party, the respondents are hit by the said principle. secondly, the decision of the respondent-railways to lease the parcel space in favour of a particular individual amounted to an unreasonable preference being given to that individual and therefore violated section 70 supra . thirdly, the learned counsel relied on the maxim delegatus non potest delegare and submitted that under sections 30 to 32, the power to fix the tariff rate is conferred only on the central government and the respondent- railways. thus, by further delegating their authority, they violate the established legal principle that a delegatee cannot sub-delegate. finally, the learned counsel for the appellant elaborated on the role of the railways as a social vehicle, by citing the case of viklad coal merchant v. union of india, 1984 1 scc 619, the relevant paragraph reads thus 13. re ground 1 railway is a common carrier and being state owned it is subject not only to the provisions of the act but also the fundamental rights guaranteed by part iii of the constitution. however much before the advent of the constitution when different railways were owned by incorporated companies, section 28 of the act precluded the different railway administrations from granting undue preference to any particular person or any particular traffic or to any particular railway administration, or subject anyone to any undue or unreasonable prejudice or disadvantage in the matter of transport of goods or passengers. railway being a state monopoly, to checkmate its monopolistic power in the larger public interest it has to be subjected to regulatory measures. simultaneously it became necessary to arm central government with power to direct railway administration to give preference in the matter of transport of the goods of the governmen

In [25]:
from google.colab import userdata

GEMINI_API_KEY = userdata.get("GEMINI_API_KEY")

print("Gemini API key loaded:", GEMINI_API_KEY is not None)

Gemini API key loaded: True

In [38]:
# Gemini client
from google import genai

client = genai.Client(
    api_key=GEMINI_API_KEY
)

print("Gemini client ready.")

Gemini client ready.

# RAG Prompt

In [28]:
def create_prompt(question, context):

    prompt = f"""
You are a legal document retrieval assistant.

Answer the user's question using ONLY the provided
retrieved legal judgment context.

Do not invent legal facts.

If the retrieved context does not contain enough
information to answer the question, clearly say:

"Insufficient information in the retrieved documents."

Provide a concise and well-structured answer.

User Question:
{question}

Retrieved Legal Context:
{context}

Answer:
"""

    return prompt

In [42]:
from google.genai.errors import ServerError
import time


def generate_answer(question, top_k=5):

    # Retrieve relevant documents
    results = retrieve_documents(
        question,
        top_k=top_k
    )

    # No relevant documents found
    if len(results) == 0:
        return (
            "Insufficient information in the retrieved documents.",
            []
        )

    # Build context
    context = build_context(results)

    # Create RAG prompt
    prompt = create_prompt(
        question,
        context
    )

    # Try multiple Gemini models

    models = [
        "gemini-3.5-flash",
        "gemini-3.5-flash-lite",
        "gemini-2.5-flash-lite"
    ]

    for model_name in models:

        try:

            print(f"Trying model: {model_name}")

            response = client.models.generate_content(
                model=model_name,
                contents=prompt
            )

            print(f"Successfully generated using: {model_name}")

            return response.text, results

        except ServerError:

            print(
                f"{model_name} is temporarily unavailable. "
                f"Trying next model..."
            )

            time.sleep(2)


    # If all models fail


    return (
        "Gemini models are temporarily unavailable. "
        "Please try again after some time.",
        results
    )

In [40]:
question = """
What was the main legal issue considered by the court?
"""

answer, sources = generate_answer(
    question,
    top_k=5
)

print(answer)

Based on the retrieved legal documents, the main legal issues considered by the courts in the respective cases are as follows:

*   **In *C.N. Ramappa Gowda v. C.C. Chandregowda* (Source 2):**
    1. Whether the High Court exceeded its jurisdiction by ordering a retrial and allowing the defendants to file a written statement and documents without legally sustainable reasons, despite prior multiple opportunities.
    2. Whether a trial court can straightway pass a decree in favor of a plaintiff when the defendant fails to file a written statement, or if it must still try the suit on its merits by critically appreciating the plaintiff's evidence.

*   **In *Chandrasingh Manibhai v. Surjit Lal Ladhamal Chhabda* (Source 5):**
    Whether the Bombay Rents, Hotel and Lodging House Rates Control Act, LVII of 1947, applies retrospectively to pending appeals or if its retrospective effect is limited only to the cases specified in Section 50 of the Act.

*   **In *Krishan Lal v. State of Jammu and Kashmir* (Source 4):**
    Whether the civil court's jurisdiction was barred under Section 20 of the J&K Government Servants Prevention of Corruption Act, 1962, when an order of dismissal was passed in violation of the mandatory inquiry procedure under Section 17(5) of the Act.

*   **In *Roop Kumar v. Mohan Thedani* (Source 1):**
    Whether the High Court correctly considered the scope and ambit of Sections 91 and 92 of the Evidence Act, and whether a sub-tenancy was barred under Section 16 of the Delhi Rent Control Act, 1958, due to the absence of the original landlord's consent.

In [44]:
question = """
What was the final decision of the court?
"""

results = retrieve_documents(
    question,
    top_k=10
)

print("Number of retrieved documents:", len(results))

for i, result in enumerate(results):

    print("\n" + "=" * 100)
    print(f"SOURCE {i + 1}")
    print("=" * 100)

    print("Similarity:",
          round(result["similarity_score"], 4))

    print("Case Category:",
          result["case_category"])

    print("Case Type:",
          result["case_type"])

    print("Case Information:",
          result["case_info"])

    print("\nRetrieved Text:")
    print(result["text"][:2000])

Number of retrieved documents: 10

====================================================================================================
SOURCE 1
====================================================================================================
Similarity: 0.6804
Case Category: civil
Case Type: appeal
Case Information: petitioner mamad hassam bhagad and others vs. respondent state of gujarat and others date of judgment 09/05/1996 bench venkataswami k.  j  bench venkataswami k.  j  anand, a.s.
j  citation 1996 air 2057 jt 1996  5  327 1996 scale  4 313 act headnote judgment j u d g m e n t k. venkataswami,j. this appeal preferred under section 19 of the terrorist and disruptive activities  prevention  act.
1987  hereinafter referred to as tada  challenges the judgment and order of the learned designated judge  tada , jamnagar dated july 1, 1994.
the learned designated judge confirmed an order of attachment of seven vessels ships under section 7a of tada pending further investigation in the matter.
at the outset we would like to make it clear that we do not propose to deal with the matter either in detail or to give a final decision in this matter in view of the fact that when the judgment under appeal was made the matter was under the investigation stage only.
in our view any opinion expressed at this stage might cause prejudice to either party and that is the reason for not going into the matter in detail or giving any final decision.
briefly stated the facts are as under in the kalyanpur police station crime register number62/93 related to a case booked for the offences punishable under sections 121, 121a, 122, 34 ipc and 25 1  a  d ,25 1  a  2 , 25 1 aa, 25 a  b , 25  a  f  of the arms act, section 20 of wireless telegraph act and sections 3,4 and 5 of tada and section 135 l  of the bombay police act.
in the course of investigation one diary of hamir sajan was found and it contained certain financial transactions relating to one haji ismail for purchasing the ships in question.
the district superintendent of police attached those ships invoking powers under section 7a of tada.
a report application number1993 was filed before the learned designated judge seeking confirmation of attachment.
the appellants claiming to be the owners of the ships in question objected to the attachment and sought revocation of such attachment before the learned designated judge.
it was argued before the learned designated judge that section 7a of tada came into force on and from 22.5.1993 and the purchases of all the ships having taken place well before that date, the provisions of tada cannot be invoked.
it was also contended that none of the persons objecting  claiming to be the owners  the attachment had ever been arrested provisions of customs act or under tada and hence prima facie section 7a of tada has no application.
it was further contended that to invoke section 7a of tada there should be knowledge or reasons to believe that properties attached are involved in terrorist activities and that requirement was not satisfied on the facts of the case.
before the learned designated judge, the designated public prosecutor after narrating the facts relating to the purchase of the seven ships in question contended that on prima facie case being made out and entertaining reason to believe that the property in question falls within the mischief of section 7a attachment in question was made and that further inquiry investigation was still going on regarding all the seven ships to conclusively find as to whether they were involved in smuggling activities or not.
it was admitted that since some of the persons were absconding and some of others had left the district therefore, at that stage, attachment could not be revoked and he prayed for confirmation of the order of attachment.
the learned designated judge bearing in mind that the investigation was still going on has given only a prima facie finding and on being satisfied with the prima facie case confirmed by the judgment under appeal.
the learned designated judge found that the main accused was one haji haji ismail and he was doing the landing activities of gold and silver articles which are smuggled goods and in order to see that government authorities do not cause any hurdles to him in carrying out such activities he was possessing automatic rifles, foreign made pistols and other latest and scientific means of communications and they were already attached and hamir sajan and other three persons were arrested.
though they were released on bail, in the first instance on the ground that tada does not apply to them, on appeal to this court, the order granting bail to then was cancelled and all the accused were taken into custody.
the learned designated judge also found, prima facie, that there was no mention at all in section 7a that the property to be investigated must be the property of an offender against whom the offence under section, 7a is to be registered.
according to the learned judge what was required to be established was that the property in relation to which the investigation was made must be having sources of purchase from the amount or proceeds of terrorism or by way of commission of terrorist activity.
therefore, the learned judge found that it was not necessary or incumbent upo

Retrieved Text:
and which had become final either because no appeal was carried to this court or, if carried, the same was dismissed. this benefit would be available to no other.

====================================================================================================
SOURCE 2
====================================================================================================
Similarity: 0.6737
Case Category: civil
Case Type: writ petition
Case Information:
supreme court of india
rupa ashok hurra vs ashok hurra anr on 10 april, 2002author j syed quadri
bench s.p. bharucha cji, s.s.m.
quadri, umesh c. banerjee, s.n. variava, shivaraj v. patil
case
number
writ petition  civil  509 of 1997

petitioner
rupa ashok hurra

respondent
ashok hurra anr.


date of judgment 10/04/2002

bench
s.p. bharucha cji s.s.m.
quadri umesh c. banerjee s.n. variava shivaraj v. patil

judgment
judgment

wi t h
 w.p. c number245/1999, w.p. c  number338/2000, w.p. c
nos.325-326/2000,w.p.
c number663/2000, w.p. c number680/2000,
w.p. c  number374/2001



Retrieved Text:
for the parties, we record that all of them at the close of the hearing of these cases conceded that the jurisdiction of this court under article 32 of the constitution cannot be invoked to challenge the validity of a final judgment order passed by this court after exhausting the remedy of review under article 137 of the constitution read with order xl rule 1 of the supreme court rules 1966. however, all the learned counsel for the parties as also the learned attorney-general who appeared as amicus curiae, on the notice of this court, adopted an unusual unanimous approach to plead that even after exhausting the remedy of review under article 137 of the constitution, an aggrieved person might be provided with an opportunity under inherent powers of this court to seek relief in cases of gross abuse of the process of the court or gross miscarriage of justice because against the order of this court the affected party cannot have recourse to any other forum. mr.shanti bhushan, the learned senior counsel appearing for the petitioner, submitted that the principle of finality of the order of this court had to be given a go-by and the case re- examined where the orders were passed without jurisdiction or in violation of the principles of natural justice, violation of any fundamental rights or where there has been gross injustice. he invited our attention to order xlvii, rule 6 of the supreme court rules, 1966 and submitted that this court had inherent jurisdiction and that cases falling in the aforementioned categories should be examined under the inherent jurisdiction of this court. according to the learned counsel article 129 would not be available to correct a judgment of this court but he pleaded that as from the order of the apex court no appeal would lie, therefore, an application, by whatever name called, which should be certified by a senior counsel in regard to existence of permissible ground, has to be entertained on any of the aforementioned grounds to correct a j

====================================================================================================
SOURCE 3
====================================================================================================
Similarity: 0.6593
Case Category: criminal
Case Type: appeal
Case Information:
supreme court of india
parbata vs state of rajasthan on 16 november, 2005equivalent citations air 2006 sc 747,  2006  2 callt 109 sc, 2006 crilj 562, 2006  1  jcr 171 sc,  2005  13 scc 398
bench b singh, r raveendran
judgment

1.


Retrieved Text:
of the evidence on record. the high court was, therefore, fully justified in setting aside the judgment and order of the trial court. 11. we find no merit in the appeal and the same is, accordingly, dismissed.

====================================================================================================
SOURCE 4
====================================================================================================
Similarity: 0.6431
Case Category: civil
Case Type: appeal
Case Information: petitioner the state of punjab ors.
vs. respondent bakhshish singh date of judgment 05/05/1997 bench k. ramaswamy, d.p. wadhwa.
act headnote judgment o r d e r the 5th day of may, 1997 present, honble mr. justice k. ramaswamy honble mr. justice d.p.wadhwa a.s. sohal, adv. for r.s. sodhi, adv.
for the appellants.


Retrieved Text:
to have interfered with the decree of the trial court. the high court dismissed it without application of the mind and ignoring the settled legal principles. the appeal is accordingly allowed. the orders of the high court and the appellate court stand set aside and that of the trial court stands confirmed number costs.

====================================================================================================
SOURCE 5
====================================================================================================
Similarity: 0.64
Case Category: civil
Case Type: appeal
Case Information:
supreme court of india
abdul rasak and ors vs kerala water authority and ors on 25 january, 2002bench r.c. lahoti, brijesh kumar
case number
appeal  civil  704-726 of 2002

petitioner
abdul rasak and ors.


respondent
kerala water authority and ors.


date of judgment 25/01/2002

bench
r.c. lahoti brijesh kumar

judgment
judgment

2002  1  scr 615



Retrieved Text:
which stand finally concluded. it cannot be doubted that on 20th october, 1994, the date on which the constitution bench delivered its judgment, the matters relating to compensation in the present case had not achieved the finality and had not stood finally concluded inasmuch as the same were pending in appeal in the high court and appeal is a continuation of original proceedings. so far as the award given by the collector is concerned, that can be said to have become final before the date of decision of constitution bench but not the award given by the civil court on reference. the high court, in its impugned judgment, formed an opinion that the law laid down by the constitution bench governed the cases at hand and, therefore, the award given by the civil court on reference, stood vitiated for want of notice to k.w.a. the high court allowed all the appeals pending before it and remanded the case for decision afresh by the reference court, after affording the parties an opportunity of adducing evidence in support of their respective contentions. feeling aggrieved by the order of remand, the claimants have filed these appeals, by special leave. shir t.l.v. iyer, the learned senior counsel for the claimant-appellants has submitted that kerala water authority is successor of public health engineering department of the state government, and bound by the proceedings conducted by or against the state government and, therefore, the constitution bench decision does not have any applicability to the facts of the present case and the high court ought not to have set aside the awards and remanded the cases to the reference court. we find it difficult to subscribe to the view so forcefully canvassed by the learned senior counsel for the appellants. k.w.a. came into existence as a statutory corporation on 1st april, 1984. it may be said to have succeeded to the liability incurred by the state government so far as the quantum of compensation awarded by the collector is concerned

====================================================================================================
SOURCE 6
====================================================================================================
Similarity: 0.6268
Case Category: civil
Case Type: appeal
Case Information: petitioner k. m. nanavati vs. respondent state of maharashtra date of judgment 24/11/1961 bench subbarao, k. bench subbarao, k. das, s.k. dayal, raghubar citation 1962 air 605 1962 scr supl.
1  567 citator info r 1964 sc1563  6  f 1974 sc1570  19  rf 1976 sc 966  32  f 1983 sc 855  16  d 1987 sc 852  9  r 1990 sc1459  24  act jury trial-charge-misdirection-reference by judge, if and when competent-plea of general exception-burden of proof-grave an sudden provocation-test-power of high court in reference-code of criminal procedure act, 5 of 1898 , 88. 307, 410, 417, 418  1 , 423 2 , 297,155  1 , 162-indian penal code, 1860  act 45 of 1860 , 88.
302, 300, exception i-indian evidence act, 1872  1 of 1872 , 8. 105.


Retrieved Text:
relied upon the words ends of justice end held that the verdict was one which no reasonable body of men could have, reached on the evidence and further laid down that the requirements of the ends of ju

====================================================================================================
SOURCE 7
====================================================================================================
Similarity: 0.6266
Case Category: civil
Case Type: appeal
Case Information: judgment amarendra nath sen, j. 1.


Retrieved Text:
out at length the facts and circumstances of this case.or the various submissions which had been made. the decision of the high court meets with our approval and we see no reason to interfere with the judgment and order passed by the high court. the appeal is accordingly dismissed with no order as to costs.

====================================================================================================
SOURCE 8
====================================================================================================
Similarity: 0.6132
Case Category: civil
Case Type: appeal
Case Information: petitioner smt.
kaushalya devi bogra and others etc.
vs. respondent the land acquisition officer, aurangabad and anr.
date of judgment15/02/1984 bench misra rangnath bench misra rangnath fazalali, syed murtaza varadarajan, a.  j  citation 1984 air 892 1984 scr  2  900 1984 scc  2  324 1984 scale  1 304 citator info r 1988 sc 943  6  r 1992 sc 666  4  rf 1992 sc2298  8  act constitution of india 1950, article 141.


Retrieved Text:
the matter had given full hearing to the parties at an earlier stage we told mr. andhyarujina, advocate, that there was no necessity for any further hearing in the matter and that we are not inclined to do so. since there is no change in the record and no additional evidence is offered and the high court judgment was pronounced on the evidence already recorded, we see no reason to differ in any way with the well considered earlier judgment of this court. we, therefore, declare that a copy of that judgment, which will be our substantive judgment, be placed on record as the judgment of this court after remand by the supreme court. we thus not only confirm the valuation and compensation awarded by the earlier bench of this court but also confirm their order as to costs. having read the judgment of the high court and considering the manner in which the first appeals have been disposed of, we have no doubts in our mind that the high court exceeded its jurisdiction in dealing with the first appeals. this court in exercise of appellate powers vested it under article 136 of the constitution had set aside the bench decision of the high court delivered in 1971 and that judgment for all intents and purposes had become non- existent. the present division bench of the high court was not entitled, by any process known to law, to resurrect that judgment into life. the direction of the appellate court is certainly binding on the courts subordinate thereto. that apart, in view of the provisions of article 41 of the constitution, all courts in india are bound to follow the decisions of this court. judicial discipline requires and decorum known to law warrants that appellate directions should be taken as binding and followed. it is appropriate to usefully recall certain observations of the house of lords in broom v. cassell company 1 therein lord hailsham, l. c. observed the fact is, and i hope it will never be necessary to say so again, that in the hierarchical system of courts which

====================================================================================================
SOURCE 9
====================================================================================================
Similarity: 0.6131
Case Category: civil
Case Type: appeal
Case Information: petitioner smt.


Retrieved Text:
the high court was not justified in ignoring distinguishing the law laid down by this court in bhim singhs case without properly appreciating the ratio of that decision. in the circumstances, we set aside the judgment of the high court under appeal and restore that of the lower appellate court in first appeal number 130 of 1963. in the result, the appeal succeeds and is allowed accordingly with no order as to costs.

====================================================================================================
SOURCE 10
====================================================================================================
Similarity: 0.6087
Case Category: civil
Case Type: appeal
Case Information: petitioner jupudi kesava rao vs. respondent pulavarthi venkata subbarao and others.


Retrieved Text:

In [45]:
question = """
What was the final decision or outcome of the court?
What did the court ultimately hold or order?
Was the case allowed, dismissed, disposed of, or otherwise decided?
"""

results = retrieve_documents(
    question,
    top_k=10
)

for i, result in enumerate(results):

    print("\n" + "=" * 100)

    print(f"SOURCE {i + 1}")
    print("Similarity:",
          round(result["similarity_score"], 4))

    print("Case Information:",
          result["case_info"])

    print("\nText:")
    print(result["text"][:1500])

====================================================================================================
SOURCE 1
Similarity: 0.6855
Case Information: judgment amarendra nath sen, j. 1.


Text:
out at length the facts and circumstances of this case.or the various submissions which had been made. the decision of the high court meets with our approval and we see no reason to interfere with the judgment and order passed by the high court. the appeal is accordingly dismissed with no order as to costs.

====================================================================================================
SOURCE 2
Similarity: 0.6847
Case Information: petitioner mamad hassam bhagad and others vs. respondent state of gujarat and others date of judgment 09/05/1996 bench venkataswami k.  j  bench venkataswami k.  j  anand, a.s.
j  citation 1996 air 2057 jt 1996  5  327 1996 scale  4 313 act headnote judgment j u d g m e n t k. venkataswami,j. this appeal preferred under section 19 of the terrorist and disruptive activities  prevention  act.
1987  hereinafter referred to as tada  challenges the judgment and order of the learned designated judge  tada , jamnagar dated july 1, 1994.
the learned designated judge confirmed an order of attachment of seven vessels ships under section 7a of tada pending further investigation in the matter.
at the outset we would like to make it clear that we do not propose to deal with the matter either in detail or to give a final decision in this matter in view of the fact that when the judgment under appeal was made the matter was under the investigation stage only.
in our view any opinion expressed at this stage might cause prejudice to either party and that is the reason for not going into the matter in detail or giving any final decision.
briefly stated the facts are as under in the kalyanpur police station crime register number62/93 related to a case booked for the offences punishable under sections 121, 121a, 122, 34 ipc and 25 1  a  d ,25 1  a  2 , 25 1 aa, 25 a  b , 25  a  f  of the arms act, section 20 of wireless telegraph act and sections 3,4 and 5 of tada and section 135 l  of the bombay police act.
in the course of investigation one diary of hamir sajan was found and it contained certain financial transactions relating to one haji ismail for purchasing the ships in question.
the district superintendent of police attached those ships invoking powers under section 7a of tada.
a report application number1993 was filed before the learned designated judge seeking confirmation of attachment.
the appellants claiming to be the owners of the ships in question objected to the attachment and sought revocation of such attachment before the learned designated judge.
it was argued before the learned designated judge that section 7a of tada came into force on and from 22.5.1993 and the purchases of all the ships having taken place well before that date, the provisions of tada cannot be invoked.
it was also contended that none of the persons objecting  claiming to be the owners  the attachment had ever been arrested provisions of customs act or under tada and hence prima facie section 7a of tada has no application.
it was further contended that to invoke section 7a of tada there should be knowledge or reasons to believe that properties attached are involved in terrorist activities and that requirement was not satisfied on the facts of the case.
before the learned designated judge, the designated public prosecutor after narrating the facts relating to the purchase of the seven ships in question contended that on prima facie case being made out and entertaining reason to believe that the property in question falls within the mischief of section 7a attachment in question was made and that further inquiry investigation was still going on regarding all the seven ships to conclusively find as to whether they were involved in smuggling activities or not.
it was admitted that since some of the persons were absconding and some of others had left the district therefore, at that stage, attachment could not be revoked and he prayed for confirmation of the order of attachment.
the learned designated judge bearing in mind that the investigation was still going on has given only a prima facie finding and on being satisfied with the prima facie case confirmed by the judgment under appeal.
the learned designated judge found that the main accused was one haji haji ismail and he was doing the landing activities of gold and silver articles which are smuggled goods and in order to see that government authorities do not cause any hurdles to him in carrying out such activities he was possessing automatic rifles, foreign made pistols and other latest and scientific means of communications and they were already attached and hamir sajan and other three persons were arrested.
though they were released on bail, in the first instance on the ground that tada does not apply to them, on appeal to this court, the order granting bail to then was cancelled and all the accused were taken into custody.
the learned designated judge also found, prima facie, that there was no mention at all in section 7a that the property to be investigated must be the property of an offender against whom the offence under section, 7a is to be registered.
according to the learned judge what was required to be established was that the property in relation to which the investigation was made must be having sources of purchase from the amount or proceeds of terrorism or by way of commission of terrorist activity.
therefore, the learned judge found that it was not necessary or incumbent upo

Text:
and which had become final either because no appeal was carried to this court or, if carried, the same was dismissed. this benefit would be available to no other.

====================================================================================================
SOURCE 3
Similarity: 0.676
Case Information:
supreme court of india
parbata vs state of rajasthan on 16 november, 2005equivalent citations air 2006 sc 747,  2006  2 callt 109 sc, 2006 crilj 562, 2006  1  jcr 171 sc,  2005  13 scc 398
bench b singh, r raveendran
judgment

1.


Text:
of the evidence on record. the high court was, therefore, fully justified in setting aside the judgment and order of the trial court. 11. we find no merit in the appeal and the same is, accordingly, dismissed.

====================================================================================================
SOURCE 4
Similarity: 0.6559
Case Information:
supreme court of india
rupa ashok hurra vs ashok hurra anr on 10 april, 2002author j syed quadri
bench s.p. bharucha cji, s.s.m.
quadri, umesh c. banerjee, s.n. variava, shivaraj v. patil
case
number
writ petition  civil  509 of 1997

petitioner
rupa ashok hurra

respondent
ashok hurra anr.


date of judgment 10/04/2002

bench
s.p. bharucha cji s.s.m.
quadri umesh c. banerjee s.n. variava shivaraj v. patil

judgment
judgment

wi t h
 w.p. c number245/1999, w.p. c  number338/2000, w.p. c
nos.325-326/2000,w.p.
c number663/2000, w.p. c number680/2000,
w.p. c  number374/2001



Text:
for the parties, we record that all of them at the close of the hearing of these cases conceded that the jurisdiction of this court under article 32 of the constitution cannot be invoked to challenge the validity of a final judgment order passed by this court after exhausting the remedy of review under article 137 of the constitution read with order xl rule 1 of the supreme court rules 1966. however, all the learned counsel for the parties as also the learned attorney-general who appeared as amicus curiae, on the notice of this court, adopted an unusual unanimous approach to plead that even after exhausting the remedy of review under article 137 of the constitution, an aggrieved person might be provided with an opportunity under inherent powers of this court to seek relief in cases of gross abuse of the process of the court or gross miscarriage of justice because against the order of this court the affected party cannot have recourse to any other forum. mr.shanti bhushan, the learned senior counsel appearing for the petitioner, submitted that the principle of finality of the order of this court had to be given a go-by and the case re- examined where the orders were passed without jurisdiction or in violation of the principles of natural justice, violation of any fundamental rights or where there has been gross injustice. he invited our attention to order xlvii, rule 6 of the supreme court rules, 1966 and submitted that this court had inherent jurisdiction and that cases falli

====================================================================================================
SOURCE 5
Similarity: 0.6553
Case Information: petitioner the state of punjab ors.
vs. respondent bakhshish singh date of judgment 05/05/1997 bench k. ramaswamy, d.p. wadhwa.
act headnote judgment o r d e r the 5th day of may, 1997 present, honble mr. justice k. ramaswamy honble mr. justice d.p.wadhwa a.s. sohal, adv. for r.s. sodhi, adv.
for the appellants.


Text:
to have interfered with the decree of the trial court. the high court dismissed it without application of the mind and ignoring the settled legal principles. the appeal is accordingly allowed. the orders of the high court and the appellate court stand set aside and that of the trial court stands confirmed number costs.

====================================================================================================
SOURCE 6
Similarity: 0.638
Case Information: petitioner prakash chander manchanda and anr.
vs. respondent smt.


Text:
defendant was only to begin on this date or an earlier date when the case was adjourned. it is therefore clear that upto the date i.e. 30th october, 1985 when the trial court closed the case of defendant there was no evidence on record on behalf of the defendant. in this view of the matter there- fore the explanation to order 17 rule 2 was not applicable at all. apparently when the defendant was absent order 17 rule 2 only permitted the court to proceed to dispose of the matter in any one of the modes provided under order 9. it is also clear that order 17 rule 3 as it stands was not applicable to the facts of this case as admittedly on the date when the evidence of defendant was closed nobody appeared for the defendant. in this view of the matter it could not be disputed that the court when proceeded to dispose of the suit on merits had committed an error. unfor- tunately even on the review application, the learned trial court went on in the controversy about order 17 rules 2 and 3 which existed before the amendment and rejected the review application and on appeal, the high court also unfortunately dismissed the appeal in limine by one word. the learned counsel for the respondent attempted to contend that in this view of law as it now stands an appli- cation under order 9 rule 13 will be maintainable. however it was suggested that there was also an objection of limita- tion about the acceptance of that applica- tion. it is apparent that the learned trial court has not consid

====================================================================================================
SOURCE 7
Similarity: 0.637
Case Information: judgment c.a. vaidialingam, j. 1.


Text:
the high court in setting aside the order of acquittal. the appeal fails and is dismissed.

====================================================================================================
SOURCE 8
Similarity: 0.6213
Case Information:
supreme court of india
chairman, state bank of india and  vs all orissa state bank officers  on 6 may, 2002equivalent citations air 2002 sc 2279, 2002  94  flr 338, jt 2002  4  sc 537, 2002 lablc 2153,  2002  iillj 562 sc,  2002  3 mlj 48 sc, 2002  4  scale 423,  2002  5 scc 669, 2002 3 scr 797, 2002  3  sct 1127 sc, 2002  3  slj 122 sc,  2002
 3 uplbec 2052
author d mohapatra
bench d mohapatra, k balakrishnan
judgment

d.p. mohapatra, j.

1.
leave is granted.


2.


Text:
passed by the high court. therefore, no interference in the matter is called for. accordingly, the appeals are dismissed, but in the circumstances of the case without any order as to costs.

====================================================================================================
SOURCE 9
Similarity: 0.6212
Case Information:
supreme court of india
rupa ashok hurra vs ashok hurra anr on 10 april, 2002author j syed quadri
bench s.p. bharucha cji, s.s.m.
quadri, umesh c. banerjee, s.n. variava, shivaraj v. patil
case
number
writ petition  civil  509 of 1997

petitioner
rupa ashok hurra

respondent
ashok hurra anr.


date of judgment 10/04/2002

bench
s.p. bharucha cji s.s.m.
quadri umesh c. banerjee s.n. variava shivaraj v. patil

judgment
judgment

wi t h
 w.p. c number245/1999, w.p. c  number338/2000, w.p. c
nos.325-326/2000,w.p.
c number663/2000, w.p. c number680/2000,
w.p. c  number374/2001



Text:
that even after the dismissal of the review petition the supreme court reconsidered its own judgment he pleaded for laying down guidelines in regard to entertaining such an application. mr.anil b.divan, the learned senior counsel, submitted that article 129 of the constitution declared this court to be a court of record so it would have inherent powers to pass appropriate orders to undo injustice to any party resulting from judgments of this court. he relied on the judgment of this court in supreme court bar associations case supra to show that such a power was exercised by this court and pleaded to fashion appropriate procedure for entertaining application to reconsider earlier judgment of this court at the instance of an aggrieved person to do justice to the parties. the learned attorney-general argued that the remedy provided under article 32 of the constitution would not be available to a person aggrieved by the final order of this court he nonetheless supported the contentions urged by other learned counsel that in case of gross miscarriage of justice, this court ought to exercise its inherent powers by entertaining an application to examine the final order of this court, even when a review was rejected, in the rarest of the rare cases. according to him where the order was passed without jurisdiction or in violation of the principles of natural justice, the case would fall in the rarest of the rare cases. he, however, contended that an order of this court could not be sa

====================================================================================================
SOURCE 10
Similarity: 0.6211
Case Information: petitioner smt.


Text:
find no ground to interfere with the impugned order and the judgments of the high court. the appeals are dismissed.

In [46]:
question = """
What was the final decision or outcome of the court?
What did the court ultimately hold or order?
Was the case allowed, dismissed, disposed of, or otherwise decided?
"""

answer, sources = generate_answer(
    question,
    top_k=10
)

print(answer)

Trying model: gemini-3.5-flash
gemini-3.5-flash is temporarily unavailable. Trying next model...
Trying model: gemini-3.5-flash-lite
Successfully generated using: gemini-3.5-flash-lite
Based on the provided retrieved legal judgment context, different cases resulted in different outcomes:

* **Dismissed:** Several appeals were dismissed by the court (Sources 1, 3, 7, 8, and 10). Specifically, some appeals found no merit and were dismissed (Sources 1, 3, and 8), one appeal failed and was dismissed (Source 7), and another resulted in the court finding no ground to interfere with the High Court's order, leading to the dismissal of the appeals (Source 10).
* **Allowed:** Certain appeals were allowed, setting aside the previous orders of the High Court and appellate court while confirming the trial court's order (Source 5), or setting aside the orders rejecting the application under order 9 rule 13 and directing the trial court to hear and dispose of the application in accordance with law, with costs (Source 6).
* **Other Decisions:** In Source 2, the court explicitly noted that it did not propose to give a final decision in the matter because it was still at the investigation stage. Source 4 and Source 9 involve discussions on the inherent powers of the court and curative petitions regarding final judgments, without a final case disposition stated in the provided text.

In [47]:
# Add Similarity Threshold
def retrieve_documents(query, top_k=5, threshold=0.30):

    query_embedding = embedding_model.encode(
        [query],
        normalize_embeddings=True
    )

    scores, indices = index.search(
        query_embedding.astype("float32"),
        top_k
    )

    results = []

    for score, idx in zip(scores[0], indices[0]):

        if score >= threshold:

            result = chunks_df.iloc[idx].to_dict()

            result["similarity_score"] = float(score)

            results.append(result)

    return results

In [48]:
# Evaluate Retrieval
evaluation_questions = [
    "What was the main legal issue considered by the court?",
    "What was the final decision?",
    "What arguments were presented before the court?",
    "What reasoning did the court provide?",
    "What relief was granted by the court?"
]

In [49]:
for question in evaluation_questions:

    results = retrieve_documents(
        question,
        top_k=5
    )

    print("\nQuestion:")
    print(question)

    print("Retrieved documents:",
          len(results))

    if results:
        print(
            "Top similarity:",
            round(
                results[0]["similarity_score"],
                4
            )
        )

Question:
What was the main legal issue considered by the court?
Retrieved documents: 5
Top similarity: 0.6287

Question:
What was the final decision?
Retrieved documents: 5
Top similarity: 0.5172

Question:
What arguments were presented before the court?
Retrieved documents: 5
Top similarity: 0.6312

Question:
What reasoning did the court provide?
Retrieved documents: 5
Top similarity: 0.6463

Question:
What relief was granted by the court?
Retrieved documents: 5
Top similarity: 0.658

In [50]:
# Create Evaluation Dataset
evaluation_data = [
    {
        "question": "What was the main legal issue?",
        "expected": "Main issue discussed in the judgment"
    },
    {
        "question": "What was the final decision?",
        "expected": "Final decision of the court"
    },
    {
        "question": "What reasoning did the court provide?",
        "expected": "Court's reasoning"
    },
    {
        "question": "What relief was granted?",
        "expected": "Relief granted by court"
    }
]

In [51]:
import os

os.makedirs("rag_artifacts", exist_ok=True)

faiss.write_index(
    index,
    "rag_artifacts/legal_judgment_faiss.index"
)

chunks_df.to_pickle(
    "rag_artifacts/legal_judgment_chunks.pkl"
)

print("RAG artifacts saved successfully.")

RAG artifacts saved successfully.

# RAG Retrieval Evaluation

In [52]:

# RAG EVALUATION QUESTIONS

evaluation_questions = [
    "What was the main legal issue considered by the court?",
    "What was the final decision or outcome of the court?",
    "What reasoning did the court provide for its decision?",
    "What arguments were presented before the court?",
    "What relief was granted by the court?",
    "What legal provision was relevant to the case?",
    "What was the court's final order?",
    "What did the court ultimately hold?"
]

print("Total evaluation questions:",
      len(evaluation_questions))

Total evaluation questions: 8

# Measure Retrieval Quality

In [53]:

# RETRIEVAL EVALUATION


evaluation_results = []

for question in evaluation_questions:

    results = retrieve_documents(
        question,
        top_k=10
    )

    if len(results) > 0:

        top_1_score = results[0]["similarity_score"]

        top_5_scores = [
            r["similarity_score"]
            for r in results[:5]
        ]

        top_10_scores = [
            r["similarity_score"]
            for r in results[:10]
        ]

        evaluation_results.append({
            "question": question,
            "top_1_similarity": top_1_score,
            "avg_top_5_similarity": np.mean(top_5_scores),
            "avg_top_10_similarity": np.mean(top_10_scores),
            "retrieved_documents": len(results)
        })

    else:

        evaluation_results.append({
            "question": question,
            "top_1_similarity": 0,
            "avg_top_5_similarity": 0,
            "avg_top_10_similarity": 0,
            "retrieved_documents": 0
        })


evaluation_df = pd.DataFrame(evaluation_results)

evaluation_df

,question,top_1_similarity,avg_top_5_similarity,avg_top_10_similarity,retrieved_documents
0,What was the main legal issue considered by th...,0.628708,0.609452,0.601982,10
1,What was the final decision or outcome of the ...,0.694777,0.658445,0.638548,10
2,What reasoning did the court provide for its d...,0.642099,0.621291,0.606790,10
3,What arguments were presented before the court?,0.631213,0.610339,0.603093,10
4,What relief was granted by the court?,0.658048,0.635227,0.621308,10
5,What legal provision was relevant to the case?,0.641855,0.634689,0.627383,10
6,What was the court's final order?,0.682260,0.659806,0.647567,10
7,What did the court ultimately hold?,0.640677,0.610234,0.592769,10

In [54]:
# Overall Retrieval Statistics
print("Average Top-1 Similarity:",
      round(
          evaluation_df["top_1_similarity"].mean(),
          4
      ))

print(
    "Average Top-5 Similarity:",
    round(
        evaluation_df["avg_top_5_similarity"].mean(),
        4
    )
)

print(
    "Average Top-10 Similarity:",
    round(
        evaluation_df["avg_top_10_similarity"].mean(),
        4
    )
)

Average Top-1 Similarity: 0.6525
Average Top-5 Similarity: 0.6299
Average Top-10 Similarity: 0.6174

# Retrieval Results

In [55]:
for _, row in evaluation_df.iterrows():

    print("\n" + "=" * 90)

    print("Question:")
    print(row["question"])

    print(
        "Top-1 Similarity:",
        round(row["top_1_similarity"], 4)
    )

    print(
        "Average Top-5:",
        round(row["avg_top_5_similarity"], 4)
    )

    print(
        "Average Top-10:",
        round(row["avg_top_10_similarity"], 4)
    )

==========================================================================================
Question:
What was the main legal issue considered by the court?
Top-1 Similarity: 0.6287
Average Top-5: 0.6095
Average Top-10: 0.602

==========================================================================================
Question:
What was the final decision or outcome of the court?
Top-1 Similarity: 0.6948
Average Top-5: 0.6584
Average Top-10: 0.6385

==========================================================================================
Question:
What reasoning did the court provide for its decision?
Top-1 Similarity: 0.6421
Average Top-5: 0.6213
Average Top-10: 0.6068

==========================================================================================
Question:
What arguments were presented before the court?
Top-1 Similarity: 0.6312
Average Top-5: 0.6103
Average Top-10: 0.6031

==========================================================================================
Question:
What relief was granted by the court?
Top-1 Similarity: 0.658
Average Top-5: 0.6352
Average Top-10: 0.6213

==========================================================================================
Question:
What legal provision was relevant to the case?
Top-1 Similarity: 0.6419
Average Top-5: 0.6347
Average Top-10: 0.6274

==========================================================================================
Question:
What was the court's final order?
Top-1 Similarity: 0.6823
Average Top-5: 0.6598
Average Top-10: 0.6476

==========================================================================================
Question:
What did the court ultimately hold?
Top-1 Similarity: 0.6407
Average Top-5: 0.6102
Average Top-10: 0.5928

# RAG Answer Evaluation

In [56]:

# GENERATE RAG ANSWERS FOR EVALUATION

rag_evaluation = []

for question in evaluation_questions:

    print("\nProcessing:")
    print(question)

    answer, sources = generate_answer(
        question,
        top_k=10
    )

    rag_evaluation.append({
        "question": question,
        "answer": answer,
        "number_of_sources": len(sources)
    })

print("\nEvaluation completed.")

Processing:
What was the main legal issue considered by the court?
Trying model: gemini-3.5-flash
gemini-3.5-flash is temporarily unavailable. Trying next model...
Trying model: gemini-3.5-flash-lite
Successfully generated using: gemini-3.5-flash-lite

Processing:
What was the final decision or outcome of the court?
Trying model: gemini-3.5-flash
Successfully generated using: gemini-3.5-flash

Processing:
What reasoning did the court provide for its decision?
Trying model: gemini-3.5-flash
gemini-3.5-flash is temporarily unavailable. Trying next model...
Trying model: gemini-3.5-flash-lite
Successfully generated using: gemini-3.5-flash-lite

Processing:
What arguments were presented before the court?
Trying model: gemini-3.5-flash
gemini-3.5-flash is temporarily unavailable. Trying next model...
Trying model: gemini-3.5-flash-lite
Successfully generated using: gemini-3.5-flash-lite

Processing:
What relief was granted by the court?
Trying model: gemini-3.5-flash
gemini-3.5-flash is temporarily unavailable. Trying next model...
Trying model: gemini-3.5-flash-lite
Successfully generated using: gemini-3.5-flash-lite

Processing:
What legal provision was relevant to the case?
Trying model: gemini-3.5-flash
gemini-3.5-flash is temporarily unavailable. Trying next model...
Trying model: gemini-3.5-flash-lite
Successfully generated using: gemini-3.5-flash-lite

Processing:
What was the court's final order?
Trying model: gemini-3.5-flash
Successfully generated using: gemini-3.5-flash

Processing:
What did the court ultimately hold?
Trying model: gemini-3.5-flash
gemini-3.5-flash is temporarily unavailable. Trying next model...
Trying model: gemini-3.5-flash-lite
Successfully generated using: gemini-3.5-flash-lite

Evaluation completed.

In [57]:
rag_evaluation_df = pd.DataFrame(
    rag_evaluation
)

rag_evaluation_df

,question,answer,number_of_sources
0,What was the main legal issue considered by th...,Insufficient information in the retrieved docu...,10
1,What was the final decision or outcome of the ...,Insufficient information in the retrieved docu...,10
2,What reasoning did the court provide for its d...,Insufficient information in the retrieved docu...,10
3,What arguments were presented before the court?,"Based on the provided retrieved documents, var...",10
4,What relief was granted by the court?,Insufficient information in the retrieved docu...,10
5,What legal provision was relevant to the case?,"Based on the provided retrieved context, multi...",10
6,What was the court's final order?,"Based on the retrieved legal documents, there ...",10
7,What did the court ultimately hold?,Insufficient information in the retrieved docu...,10

In [58]:
rag_evaluation_df.to_csv(
    "rag_evaluation_results.csv",
    index=False
)

evaluation_df.to_csv(
    "retrieval_evaluation_results.csv",
    index=False
)

print("Evaluation files saved successfully.")

Evaluation files saved successfully.

In [59]:
def expand_legal_query(question):

    query_expansions = {

        "final decision": """
        final decision final order court held
        judgment outcome disposed dismissed allowed
        relief granted order of the court
        """,

        "main legal issue": """
        main legal issue issue before the court
        question of law legal question
        """,

        "reasoning": """
        reasoning court observed court held
        rationale findings legal reasoning
        """,

        "relief": """
        relief granted remedy order direction
        final relief granted by the court
        """
    }

    expanded_query = question

    question_lower = question.lower()

    for keyword, expansion in query_expansions.items():

        if keyword in question_lower:

            expanded_query += " " + expansion

    return expanded_query

In [60]:
# Improved Retrieval Function
def retrieve_legal_documents(
    question,
    top_k=10
):

    # Expand legal query
    expanded_query = expand_legal_query(
        question
    )

    # Retrieve documents
    results = retrieve_documents(
        expanded_query,
        top_k=top_k
    )

    return results

In [61]:
question = """
What was the final decision of the court?
"""

results = retrieve_legal_documents(
    question,
    top_k=10
)

for i, result in enumerate(results):

    print("\n" + "=" * 90)

    print("SOURCE:", i + 1)

    print(
        "Similarity:",
        round(
            result["similarity_score"],
            4
        )
    )

    print(
        "Case Information:",
        result["case_info"]
    )

    print("\nText:")
    print(result["text"][:1500])

==========================================================================================
SOURCE: 1
Similarity: 0.7111
Case Information: petitioner mamad hassam bhagad and others vs. respondent state of gujarat and others date of judgment 09/05/1996 bench venkataswami k.  j  bench venkataswami k.  j  anand, a.s.
j  citation 1996 air 2057 jt 1996  5  327 1996 scale  4 313 act headnote judgment j u d g m e n t k. venkataswami,j. this appeal preferred under section 19 of the terrorist and disruptive activities  prevention  act.
1987  hereinafter referred to as tada  challenges the judgment and order of the learned designated judge  tada , jamnagar dated july 1, 1994.
the learned designated judge confirmed an order of attachment of seven vessels ships under section 7a of tada pending further investigation in the matter.
at the outset we would like to make it clear that we do not propose to deal with the matter either in detail or to give a final decision in this matter in view of the fact that when the judgment under appeal was made the matter was under the investigation stage only.
in our view any opinion expressed at this stage might cause prejudice to either party and that is the reason for not going into the matter in detail or giving any final decision.
briefly stated the facts are as under in the kalyanpur police station crime register number62/93 related to a case booked for the offences punishable under sections 121, 121a, 122, 34 ipc and 25 1  a  d ,25 1  a  2 , 25 1 aa, 25 a  b , 25  a  f  of the arms act, section 20 of wireless telegraph act and sections 3,4 and 5 of tada and section 135 l  of the bombay police act.
in the course of investigation one diary of hamir sajan was found and it contained certain financial transactions relating to one haji ismail for purchasing the ships in question.
the district superintendent of police attached those ships invoking powers under section 7a of tada.
a report application number1993 was filed before the learned designated judge seeking confirmation of attachment.
the appellants claiming to be the owners of the ships in question objected to the attachment and sought revocation of such attachment before the learned designated judge.
it was argued before the learned designated judge that section 7a of tada came into force on and from 22.5.1993 and the purchases of all the ships having taken place well before that date, the provisions of tada cannot be invoked.
it was also contended that none of the persons objecting  claiming to be the owners  the attachment had ever been arrested provisions of customs act or under tada and hence prima facie section 7a of tada has no application.
it was further contended that to invoke section 7a of tada there should be knowledge or reasons to believe that properties attached are involved in terrorist activities and that requirement was not satisfied on the facts of the case.
before the learned designated judge, the designated public prosecutor after narrating the facts relating to the purchase of the seven ships in question contended that on prima facie case being made out and entertaining reason to believe that the property in question falls within the mischief of section 7a attachment in question was made and that further inquiry investigation was still going on regarding all the seven ships to conclusively find as to whether they were involved in smuggling activities or not.
it was admitted that since some of the persons were absconding and some of others had left the district therefore, at that stage, attachment could not be revoked and he prayed for confirmation of the order of attachment.
the learned designated judge bearing in mind that the investigation was still going on has given only a prima facie finding and on being satisfied with the prima facie case confirmed by the judgment under appeal.
the learned designated judge found that the main accused was one haji haji ismail and he was doing the landing activities of gold and silver articles which are smuggled goods and in order to see that government authorities do not cause any hurdles to him in carrying out such activities he was possessing automatic rifles, foreign made pistols and other latest and scientific means of communications and they were already attached and hamir sajan and other three persons were arrested.
though they were released on bail, in the first instance on the ground that tada does not apply to them, on appeal to this court, the order granting bail to then was cancelled and all the accused were taken into custody.
the learned designated judge also found, prima facie, that there was no mention at all in section 7a that the property to be investigated must be the property of an offender against whom the offence under section, 7a is to be registered.
according to the learned judge what was required to be established was that the property in relation to which the investigation was made must be having sources of purchase from the amount or proceeds of terrorism or by way of commission of terrorist activity.
therefore, the learned judge found that it was not necessary or incumbent upo

Text:
and which had become final either because no appeal was carried to this court or, if carried, the same was dismissed. this benefit would be available to no other.

==========================================================================================
SOURCE: 2
Similarity: 0.6867
Case Information:
supreme court of india
parbata vs state of rajasthan on 16 november, 2005equivalent citations air 2006 sc 747,  2006  2 callt 109 sc, 2006 crilj 562, 2006  1  jcr 171 sc,  2005  13 scc 398
bench b singh, r raveendran
judgment

1.


Text:
of the evidence on record. the high court was, therefore, fully justified in setting aside the judgment and order of the trial court. 11. we find no merit in the appeal and the same is, accordingly, dismissed.

==========================================================================================
SOURCE: 3
Similarity: 0.6837
Case Information:
supreme court of india
rupa ashok hurra vs ashok hurra anr on 10 april, 2002author j syed quadri
bench s.p. bharucha cji, s.s.m.
quadri, umesh c. banerjee, s.n. variava, shivaraj v. patil
case
number
writ petition  civil  509 of 1997

petitioner
rupa ashok hurra

respondent
ashok hurra anr.


date of judgment 10/04/2002

bench
s.p. bharucha cji s.s.m.
quadri umesh c. banerjee s.n. variava shivaraj v. patil

judgment
judgment

wi t h
 w.p. c number245/1999, w.p. c  number338/2000, w.p. c
nos.325-326/2000,w.p.
c number663/2000, w.p. c number680/2000,
w.p. c  number374/2001



Text:
that even after the dismissal of the review petition the supreme court reconsidered its own judgment he pleaded for laying down guidelines in regard to entertaining such an application. mr.anil b.divan, the learned senior counsel, submitted that article 129 of the constitution declared this court to be a court of record so it would have inherent powers to pass appropriate orders to undo injustice to any party resulting from judgments of this court. he relied on the judgment of this court in supreme court bar associations case supra to show that such a power was exercised by this court and pleaded to fashion appropriate procedure for entertaining application to reconsider earlier judgment of this court at the instance of an aggrieved person to do justice to the parties. the learned attorney-general argued that the remedy provided under article 32 of the constitution would not be available to a person aggrieved by the final order of this court he nonetheless supported the contentions urged by other learned counsel that in case of gross miscarriage of justice, this court ought to exercise its inherent powers by entertaining an application to examine the final order of this court, even when a review was rejected, in the rarest of the rare cases. according to him where the order was passed without jurisdiction or in violation of the principles of natural justice, the case would fall in the rarest of the rare cases. he, however, contended that an order of this court could not be sa

==========================================================================================
SOURCE: 4
Similarity: 0.6803
Case Information: reportable in the supreme court of india civil appellate jurisdiction civil appeal number5817 of 2012 agnigundala venkata ranga rao .appellant s  versus indukuru ramachandra reddy  dead  by lrs. ors.


Text:
in reversing the judgment decree passed by the trial court. the submission of the learned counsel, in substance, was that the judgment of the trial court, which had rightly decreed the appellants suit, should be restored. it is this submission, which learned counsel elaborated by pointing out various provisions of the two acts and the exhibits and findings of the two courts below. 15 in reply, learned senior counsel for the respondents supported the impugned judgment and contended that no case is made out to interfere in the impugned order and hence appeal deserves to be dismissed. 16 before we consider the merits of the case, it is apposite to deal with one question which though arises, was not argued by pointing out the relevant provisions governing the question. 17 as mentioned above, this appeal is filed on a certificate granted by the high court single judge on the oral application made by the appellant immediately after the pronouncement of the impugned judgment as provided under article 134-a of the constitution. the order granting certificate is a part of the impugned judgment in its concluding para which reads thus learned counsel for the respondent seeks leave of this court to prefer an appeal against this judgment. accordingly, leave is granted. 18 what is the true interpretation of articles 133 and 134-a of the constitution and who can grant the certificate of fitness to appeal to the supreme court remains no more res integra. it is settled by the decision of this

==========================================================================================
SOURCE: 5
Similarity: 0.68
Case Information: case number appeal  civil  984-986 of 2005 petitioner m s trig guards force ltd respondent maharashtra indus.
dev. corpn.
ors date of judgment 06/12/2007 bench dr. arijit pasayat p. sathasivam judgment judgment civil appeal numbers 984-986 of 2005


Text:
ends of justice would be met by fresh disposal after affording opportunity to all the parties. it is made clear that we are not expressing anything on the stand taken by the appellant as well as by the respondents including midc. in view of the same, we set aside the order dated 17.2.2003 passed by the high court in w.p. number 864 of 2003 and restore the said writ petition on its file. the high court is requested to dispose of the same afresh after affording opportunity to all the parties. they are at liberty to place their respective claim by way of an affidavit counter affidavit supported by documents within a period of four weeks from the date of receipt of the copy of this judgment and thereafter it is for the division bench of the high court to decide the writ petition on merits as early as possible. 8 the civil appeals are disposed of on the above terms. no costs.

==========================================================================================
SOURCE: 6
Similarity: 0.678
Case Information:
supreme court of india
rupa ashok hurra vs ashok hurra anr on 10 april, 2002author j syed quadri
bench s.p. bharucha cji, s.s.m.
quadri, umesh c. banerjee, s.n. variava, shivaraj v. patil
case
number
writ petition  civil  509 of 1997

petitioner
rupa ashok hurra

respondent
ashok hurra anr.


date of judgment 10/04/2002

bench
s.p. bharucha cji s.s.m.
quadri umesh c. banerjee s.n. variava shivaraj v. patil

judgment
judgment

wi t h
 w.p. c number245/1999, w.p. c  number338/2000, w.p. c
nos.325-326/2000,w.p.
c number663/2000, w.p. c number680/2000,
w.p. c  number374/2001



Text:
for the parties, we record that all of them at the close of the hearing of these cases conceded that the jurisdiction of this court under article 32 of the constitution cannot be invoked to challenge the validity of a final judgment order passed by this court after exhausting the remedy of review under article 137 of the constitution read with order xl rule 1 of the supreme court rules 1966. however, all the learned counsel for the parties as also the learned attorney-general who appeared as amicus curiae, on the notice of this court, adopted an unusual unanimous approach to plead that even after exhausting the remedy of review under article 137 of the constitution, an aggrieved person might be provided with an opportunity under inherent powers of this court to seek relief in cases of gross abuse of the process of the court or gross miscarriage of justice because against the order of this court the affected party cannot have recourse to any other forum. mr.shanti bhushan, the learned senior counsel appearing for the petitioner, submitted that the principle of finality of the order of this court had to be given a go-by and the case re- examined where the orders were passed without jurisdiction or in violation of the principles of natural justice, violation of any fundamental rights or where there has been gross injustice. he invited our attention to order xlvii, rule 6 of the supreme court rules, 1966 and submitted that this court had inherent jurisdiction and that cases falli

==========================================================================================
SOURCE: 7
Similarity: 0.6778
Case Information: in the supreme court of india civil appellate jurisdiction civil appeal number 2825 of 2015 arising out of slp c  number 30338 of 2014 state of west bengal and others appellants versus r.k.b.k. limited anr.
respondents j u d g m e n t dipak misra, j. in this appeal, by special leave, the legal substantiality and acceptability of the judgment and order dated 29.08.2014 passed by the division bench of the high court of calcutta in ast number 177/2013 whereby it has overturned the decision of the learned single judge requiring the respondent-writ petitioner to knock at the doors of the alternative forum by way of appeal, on the foundation that the authority that had passed the adverse order against the first respondent had no jurisdiction, and assuming he had the jurisdiction, it stood extinguished by expiration of the time limit stipulated in certain paragraphs of the west bengal kerosene oil control order, 1968  for brevity, the control order , is called in question.
2. the facts which need to be exposited for adjudication of this appeal are that the first respondent was granted the licence for carrying on the business of superior kerosene oil as an agent by the joint director of consumer goods, west bengal in accordance with the paragraph 5 1  of the control order.
the monthly allocation of public distribution system of superior kerosene oil to the said respondent was fixed by the director of consumer goods, west bengal at 1,82,000 litres per month.
on 10.8.2012 a physical inspection was carried out by the area inspector attached to the office of the sub divisional controller, food and supplies, burdwan  for short, scfs  at the depot of the respondent.
the concerned inspector submitted the report to the scfs stating that 71,494 litres of superior kerosene oil had been delivered in excess by the dealer.
on 8.4.2013, the scfs issued a notice seeking explanation about the discrepancy pointed out by the area inspector.
on receipt of the said show cause notice, the first respondent submitted his explanation on 16.4.2013.
the scfs afforded an opportunity of personal hearing to the dealer on 3.5.2013 and the same was availed of.
after conducting the enquiry, the scfs forwarded the entire record to the district controller, food and supplies department, burdwan, who in turn sent the entire case records to the director of consumer goods for appropriate decision.
after scrutiny of the records, the director of consumer goods issued a show cause notice to the dealer on 26.6.2013.
the first respondent replied to the same on 28.6.2013 through his counsel stating, inter alia, that under the control order, after the licence is issued to an agent by the office of the director, the district magistrate having jurisdiction or any officer authorised by him, is alone empowered to look into the functioning of the said agency and to give directions to him and or initiate action against the concerned agent.
additionally, it was also put forth that the second show cause notice on the self-same allegations was untenable in law and accordingly prayer was made to withdraw and or rescind the notice and take steps for disposal of the matter in terms of the provisions of the control order.
3. as the factual matrix would further undrape, the director of consumer goods, vide order dated 22.7.2013 narrated the facts in detail and came to hold that scfs has the authority to ask for explanation regarding distribution of superior kerosene oil in his jurisdiction and that the director of consumer goods being the licensing authority, can exercise the power to issue show cause notice and after giving the delinquent agent a fair opportunity of being heard, pass appropriate orders.
the said order also would reflect that the counsel for the first respondent had appeared before the director on 17.7.2013.
the concerned director analysed the factual matrix and in exercise of power conferred on him under paragraph 9 ii  of the control order imposed a penalty of rs.26,08,816.00 and further directed reduction of monthly allocation of superior kerosene oil of the agent by 12,000 litres for a period of one year.
4. the order passed by the director was assailed by the agent in w.p.no.
25204  w  of 2013.
the learned single judge vide order dated 22.08.2013 referred to paragraph 10 of the control order which provides for an appeal to be preferred and accordingly directed that if the agent prefers an appeal by 6.9.2013, the appellate authority shall dispose of the same by 31.12.2013.
the learned single judge further directed that the agent shall maintain with utmost care an inventory of stocks and accounts for periodical submission to the authorities and the penalty amount should be deposited by 6.9.2013 and the said penalty amount shall be kept in a separate interest bearing account.
5. being aggrieved by the aforesaid order, the respondents 1 and 2 preferred an appeal being ast number 177 of 2013 before the division bench.
it was urged in the intra-court appeal

Text:

In [63]:

# SEARCH FOR A SPECIFIC CASE


case_name = "Kikiben Ors vs Balvantlal Shivlal"

# Search case information directly
case_matches = chunks_df[
    chunks_df["case_info"]
    .str.contains(
        "Kikiben",
        case=False,
        na=False
    )
]

print("Matching chunks:", len(case_matches))

case_matches.head()

Matching chunks: 2

,case_id,chunk_id,case_category,case_type,case_info,text
38072,7064,0,civil,appeal,\nsupreme court of india\nkikiben ors vs balva...,Case Category: civil Case Type: appeal Case In...
38073,7064,1,civil,appeal,\nsupreme court of india\nkikiben ors vs balva...,not correct and is contrary to the decision of...

In [64]:
# Display the matching case information

for i, row in case_matches.head(5).iterrows():

    print("=" * 100)

    print("Case Information:")
    print(row["case_info"])

    print("\nJudgment Text:")
    print(row["text"][:2000])

    print()

====================================================================================================
Case Information:

supreme court of india
kikiben ors vs balvantlal shivlal  dead  by lrs.
 on 15 september, 1999equivalent citations 2000  1  scale 357
bench k venkataswami, d wadhwa
order

1.
application for substitution is allowed.


2.


Judgment Text:
Case Category: civil Case Type: appeal Case Information: supreme court of india kikiben ors vs balvantlal shivlal dead by lrs. on 15 september, 1999equivalent citations 2000 1 scale 357 bench k venkataswami, d wadhwa order 1. application for substitution is allowed. 2. Judgment: these appeals are preferred against the common judgment and order of the gujarat high court in first appeal numbers 387/77 and 388/77 dated 12.10.1984. the appellants are the defendants in the original suit. the respondents-plaintiffs preferred spl. civil suits 131/74 132/74 for enforcement of a testamentary term in their favour and against the appellants defendants herein. the suits were decreed on 31.1.1977. 3. the case of the appellants defendants was that the property in dispute belonged to their father one harkishandas who became the sole owner of the property in the year 1946. the said harkishandas executed a will on 30.11.1954 giving life interest to his wife and absolute interest in favour of his brother. harkishandas died on 11.2.1959. it is stated that after the death of harkishandas the will was probated jointly by the widow of harkishandas mother of the appellants and brother of harkishandas as executors under the will. after the death of the widow in the year 1967 disputes have arisen. 4. the appellants herein who are daughters of harkishandas claimed absolute right in the suit properties. the trial court however decreed the suits of the respondents and denied the rights in the suit properties to the defendants. on appeal, the high court confirmed the judgment and decree of the trial court holding that section 14 2 of the hindu succession act, 1956 will apply to the facts of this case and therefore widow of harkishandas will get only limited interests. these appeals are against the judgment of the high court. 5. learned senior counsel mr. dholkia for the appellants brought to our notice a judgment of this court in ram kali v. choudhri ajit shankar , wherein, more or less under t

====================================================================================================
Case Information:

supreme court of india
kikiben ors vs balvantlal shivlal  dead  by lrs.
 on 15 september, 1999equivalent citations 2000  1  scale 357
bench k venkataswami, d wadhwa
order

1.
application for substitution is allowed.


2.


Judgment Text:
not correct and is contrary to the decision of this court as noticed above. this position is also not disputed. 7. in the circumstances, we are of the view that the high court was not right in dismissing the appeals by confirming the decree of the trial court. the appeals are allowed. suits filed by the respondents stand dismissed. however, there will be no order as to costs. the interim applications are accordingly disposed of.

In [65]:
def retrieve_case_specific_documents(
    case_name,
    question,
    top_k=10
):


    # Find chunks belonging to the requested case

    case_keyword = case_name.split()[0]

    case_matches = chunks_df[
        chunks_df["case_info"]
        .str.contains(
            case_keyword,
            case=False,
            na=False
        )
    ].copy()

    print(
        "Case-related chunks found:",
        len(case_matches)
    )

    # If case not found


    if len(case_matches) == 0:

        return []


    # Embed the question


    query_embedding = embedding_model.encode(
        [question],
        normalize_embeddings=True
    )


    # Embed only the case chunks


    case_embeddings = embedding_model.encode(
        case_matches["text"].tolist(),
        normalize_embeddings=True,
        show_progress_bar=False
    )

    # Calculate similarity


    scores = np.dot(
        case_embeddings,
        query_embedding[0]
    )

    case_matches["similarity_score"] = scores


    # Sort by relevance


    case_matches = case_matches.sort_values(
        "similarity_score",
        ascending=False
    )


    # Return Top-K


    return case_matches.head(top_k).to_dict(
        orient="records"
    )

In [66]:
question = """
What was the final decision or order of the court?
"""

sources = retrieve_case_specific_documents(
    "Kikiben Ors vs Balvantlal Shivlal",
    question,
    top_k=5
)

for i, source in enumerate(sources):

    print("\n" + "=" * 100)

    print("SOURCE:", i + 1)

    print(
        "Similarity:",
        round(
            source["similarity_score"],
            4
        )
    )

    print(
        "Case Information:",
        source["case_info"]
    )

    print("\nText:")
    print(source["text"][:2000])

Case-related chunks found: 2

====================================================================================================
SOURCE: 1
Similarity: 0.5769
Case Information:
supreme court of india
kikiben ors vs balvantlal shivlal  dead  by lrs.
 on 15 september, 1999equivalent citations 2000  1  scale 357
bench k venkataswami, d wadhwa
order

1.
application for substitution is allowed.


2.


Text:
not correct and is contrary to the decision of this court as noticed above. this position is also not disputed. 7. in the circumstances, we are of the view that the high court was not right in dismissing the appeals by confirming the decree of the trial court. the appeals are allowed. suits filed by the respondents stand dismissed. however, there will be no order as to costs. the interim applications are accordingly disposed of.

====================================================================================================
SOURCE: 2
Similarity: 0.4361
Case Information:
supreme court of india
kikiben ors vs balvantlal shivlal  dead  by lrs.
 on 15 september, 1999equivalent citations 2000  1  scale 357
bench k venkataswami, d wadhwa
order

1.
application for substitution is allowed.


2.


Text:
Case Category: civil Case Type: appeal Case Information: supreme court of india kikiben ors vs balvantlal shivlal dead by lrs. on 15 september, 1999equivalent citations 2000 1 scale 357 bench k venkataswami, d wadhwa order 1. application for substitution is allowed. 2. Judgment: these appeals are preferred against the common judgment and order of the gujarat high court in first appeal numbers 387/77 and 388/77 dated 12.10.1984. the appellants are the defendants in the original suit. the respondents-plaintiffs preferred spl. civil suits 131/74 132/74 for enforcement of a testamentary term in their favour and against the appellants defendants herein. the suits were decreed on 31.1.1977. 3. the case of the appellants defendants was that the property in dispute belonged to their father one harkishandas who became the sole owner of the property in the year 1946. the said harkishandas executed a will on 30.11.1954 giving life interest to his wife and absolute interest in favour of his brother. harkishandas died on 11.2.1959. it is stated that after the death of harkishandas the will was probated jointly by the widow of harkishandas mother of the appellants and brother of harkishandas as executors under the will. after the death of the widow in the year 1967 disputes have arisen. 4. the appellants herein who are daughters of harkishandas claimed absolute right in the suit properties. the trial court however decreed the suits of the respondents and denied the rights in the suit properties to the defendants. on appeal, the high court confirmed the judgment and decree of the trial court holding that section 14 2 of the hindu succession act, 1956 will apply to the facts of this case and therefore widow of harkishandas will get only limited interests. these appeals are against the judgment of the high court. 5. learned senior counsel mr. dholkia for the appellants brought to our notice a judgment of this court in ram kali v. choudhri ajit shankar , wherein, more or less under t

In [67]:
def generate_case_answer(
    case_name,
    question,
    top_k=5
):

    # -----------------------------------
    # Retrieve case-specific documents
    # -----------------------------------

    sources = retrieve_case_specific_documents(
        case_name,
        question,
        top_k=top_k
    )

    if len(sources) == 0:

        return (
            "The requested case could not be found "
            "in the retrieved dataset.",
            []
        )

    # -----------------------------------
    # Build context
    # -----------------------------------

    context_parts = []

    for i, source in enumerate(sources):

        context_parts.append(
            f"""
SOURCE {i + 1}

Case:
{source["case_info"]}

Relevant Judgment:
{source["text"]}
"""
        )

    context = "\n".join(context_parts)

    # -----------------------------------
    # Legal RAG prompt
    # -----------------------------------

    prompt = f"""
You are a legal document retrieval assistant.

The user is asking about this specific Indian
Supreme Court case:

{case_name}

Answer the question ONLY using the retrieved
judgment excerpts below.

Do not use outside knowledge.

If the retrieved excerpts contain the final
decision, clearly state what the court decided.

Question:
{question}

Retrieved Judgment Context:
{context}

Answer:
"""

    # -----------------------------------
    # Gemini models with fallback
    # -----------------------------------

    models = [
        "gemini-3.5-flash",
        "gemini-3.5-flash-lite",
        "gemini-2.5-flash-lite"
    ]

    for model_name in models:

        try:

            print(
                f"Trying model: {model_name}"
            )

            response = client.models.generate_content(
                model=model_name,
                contents=prompt
            )

            print(
                f"Successfully generated using: "
                f"{model_name}"
            )

            return response.text, sources

        except ServerError:

            print(
                f"{model_name} unavailable. "
                f"Trying next model..."
            )

            time.sleep(2)

    return (
        "Gemini models are temporarily unavailable.",
        sources
    )

In [68]:
case_name = "Kikiben Ors vs Balvantlal Shivlal"

question = """
What was the final decision of the court?
"""

answer, sources = generate_case_answer(
    case_name,
    question,
    top_k=5
)

print("\nFINAL ANSWER")
print("=" * 80)
print(answer)

Case-related chunks found: 2
Trying model: gemini-3.5-flash
gemini-3.5-flash unavailable. Trying next model...
Trying model: gemini-3.5-flash-lite
Successfully generated using: gemini-3.5-flash-lite

FINAL ANSWER
================================================================================
Based on the retrieved judgment excerpts, the final decision of the court was:

* The application for substitution was allowed.
* The appeals were allowed, and the High Court's judgment confirming the trial court's decree was set aside.
* The suits filed by the respondents stand dismissed.
* There was no order as to costs.

# Final RAG Pipeline

In [69]:

# FINAL LEGAL RAG PIPELINE


def legal_rag_pipeline(
    case_name,
    question,
    top_k=5
):
    """
    Complete case-specific Legal RAG pipeline.

    Flow:
    Case Name
        ↓
    Case-specific Retrieval
        ↓
    Relevant Context
        ↓
    Gemini LLM
        ↓
    Grounded Answer + Sources
    """

    # Retrieve relevant case chunks


    sources = retrieve_case_specific_documents(
        case_name,
        question,
        top_k=top_k
    )

    # Handle missing case


    if len(sources) == 0:

        return {
            "answer": (
                "The requested case could not be found "
                "in the retrieved dataset."
            ),
            "sources": []
        }

    # Build context

    context_parts = []

    for i, source in enumerate(sources):

        context_parts.append(
            f"""
SOURCE {i + 1}

Case Information:
{source["case_info"]}

Relevant Judgment:
{source["text"]}
"""
        )

    context = "\n".join(context_parts)

    # Create grounded legal prompt

    prompt = f"""
You are a legal document retrieval assistant.

You must answer the user's question using ONLY
the retrieved judgment excerpts provided below.

Do not use outside knowledge.

Do not invent legal facts.

If the retrieved context does not contain enough
information, clearly state:

"Insufficient information in the retrieved documents."

Case:
{case_name}

Question:
{question}

Retrieved Judgment Context:
{context}

Provide a concise and factual answer.

Answer:
"""


    # Gemini model fallback

    models = [
        "gemini-3.5-flash",
        "gemini-3.5-flash-lite",
        "gemini-2.5-flash-lite"
    ]

    for model_name in models:

        try:

            print(
                f"Trying model: {model_name}"
            )

            response = client.models.generate_content(
                model=model_name,
                contents=prompt
            )

            print(
                f"Successfully generated using: "
                f"{model_name}"
            )

            return {
                "answer": response.text,
                "sources": sources,
                "model": model_name
            }

        except ServerError:

            print(
                f"{model_name} unavailable. "
                f"Trying next model..."
            )

            time.sleep(2)

    # All models unavailable

    return {
        "answer": (
            "Gemini models are temporarily unavailable. "
            "Please try again later."
        ),
        "sources": sources,
        "model": None
    }

# Test Final Pipeline

In [70]:

# FINAL PIPELINE TEST

case_name = "Kikiben Ors vs Balvantlal Shivlal"

question = """
What was the final decision of the court?
"""

result = legal_rag_pipeline(
    case_name=case_name,
    question=question,
    top_k=5
)

print("\nFINAL ANSWER")
print("=" * 80)
print(result["answer"])

print("\nMODEL USED")
print("=" * 80)
print(result["model"])

print("\nRETRIEVED SOURCES")
print("=" * 80)

for i, source in enumerate(result["sources"]):

    print(f"\nSource {i + 1}")

    print(
        "Similarity:",
        round(
            source["similarity_score"],
            4
        )
    )

    print(
        "Case:",
        source["case_info"]
    )

Case-related chunks found: 2
Trying model: gemini-3.5-flash
Successfully generated using: gemini-3.5-flash

FINAL ANSWER
================================================================================
Based on the retrieved documents, the final decision of the court was as follows:

1. The application for substitution is allowed.
2. The appeals are allowed.
3. The suits filed by the respondents stand dismissed.
4. There will be no order as to costs.
5. The interim applications are disposed of accordingly.

MODEL USED
================================================================================
gemini-3.5-flash

RETRIEVED SOURCES
================================================================================

Source 1
Similarity: 0.5846
Case:
supreme court of india
kikiben ors vs balvantlal shivlal  dead  by lrs.
 on 15 september, 1999equivalent citations 2000  1  scale 357
bench k venkataswami, d wadhwa
order

1.
application for substitution is allowed.


2.


Source 2
Similarity: 0.4397
Case:
supreme court of india
kikiben ors vs balvantlal shivlal  dead  by lrs.
 on 15 september, 1999equivalent citations 2000  1  scale 357
bench k venkataswami, d wadhwa
order

1.
application for substitution is allowed.


2.

# Test Multiple Questions

In [71]:
# ==========================================
# MULTIPLE QUESTION TEST
# ==========================================

case_name = "Kikiben Ors vs Balvantlal Shivlal"

test_questions = [
    "What was the final decision of the court?",
    "What was the main legal issue in this case?",
    "What did the court decide regarding the appeals?",
    "What happened to the suits filed by the respondents?",
    "Did the court award any costs?"
]

for question in test_questions:

    print("\n")
    print("=" * 100)
    print("QUESTION:")
    print(question)
    print("=" * 100)

    result = legal_rag_pipeline(
        case_name,
        question,
        top_k=5
    )

    print("\nANSWER:")
    print(result["answer"])

    print(
        "\nMODEL:",
        result["model"]
    )

====================================================================================================
QUESTION:
What was the final decision of the court?
====================================================================================================
Case-related chunks found: 2
Trying model: gemini-3.5-flash
gemini-3.5-flash unavailable. Trying next model...
Trying model: gemini-3.5-flash-lite
Successfully generated using: gemini-3.5-flash-lite

ANSWER:
Based on the retrieved documents, the final decision of the court was:

* The application for substitution is allowed.
* The appeals are allowed.
* The suits filed by the respondents stand dismissed.
* There will be no order as to costs.
* The interim applications are disposed of accordingly.

MODEL: gemini-3.5-flash-lite


====================================================================================================
QUESTION:
What was the main legal issue in this case?
====================================================================================================
Case-related chunks found: 2
Trying model: gemini-3.5-flash
gemini-3.5-flash unavailable. Trying next model...
Trying model: gemini-3.5-flash-lite
Successfully generated using: gemini-3.5-flash-lite

ANSWER:
Based on the retrieved documents, the main legal issue involved whether Section 14(1) or Section 14(2) of the Hindu Succession Act, 1956, applied to the facts of the case—specifically, whether the testator's widow received only a limited interest (under Section 14(2), as held by the High Court) or whether her limited estate enlarged into an absolute one (under Section 14(1)). A secondary issue raised by the respondents was whether the widow's participation in the probate proceedings amounted to an alienation of her interest in the property in favor of the respondents.

MODEL: gemini-3.5-flash-lite


====================================================================================================
QUESTION:
What did the court decide regarding the appeals?
====================================================================================================
Case-related chunks found: 2
Trying model: gemini-3.5-flash
gemini-3.5-flash unavailable. Trying next model...
Trying model: gemini-3.5-flash-lite
Successfully generated using: gemini-3.5-flash-lite

ANSWER:
Based on the retrieved documents, the court decided that the appeals are allowed, and the suits filed by the respondents stand dismissed. There was no order as to costs, and the interim applications were disposed of accordingly.

MODEL: gemini-3.5-flash-lite


====================================================================================================
QUESTION:
What happened to the suits filed by the respondents?
====================================================================================================
Case-related chunks found: 2
Trying model: gemini-3.5-flash
gemini-3.5-flash unavailable. Trying next model...
Trying model: gemini-3.5-flash-lite
Successfully generated using: gemini-3.5-flash-lite

ANSWER:
Based on the retrieved documents, the suits filed by the respondents stand dismissed.

MODEL: gemini-3.5-flash-lite


====================================================================================================
QUESTION:
Did the court award any costs?
====================================================================================================
Case-related chunks found: 2
Trying model: gemini-3.5-flash
gemini-3.5-flash unavailable. Trying next model...
Trying model: gemini-3.5-flash-lite
Successfully generated using: gemini-3.5-flash-lite

ANSWER:
Based on the retrieved documents, the court stated, "there will be no order as to costs."

MODEL: gemini-3.5-flash-lite

# Create a Simple Evaluation Table

In [74]:

# RETRIEVAL-ONLY EVALUATION

retrieval_results = []

case_name = "Kikiben Ors vs Balvantlal Shivlal"

for question in test_questions:

    sources = retrieve_case_specific_documents(
        case_name,
        question,
        top_k=5
    )

    if len(sources) > 0:

        top_similarity = sources[0]["similarity_score"]

        average_similarity = np.mean([
            source["similarity_score"]
            for source in sources
        ])

    else:

        top_similarity = 0
        average_similarity = 0

    retrieval_results.append({
        "case": case_name,
        "question": question,
        "sources_retrieved": len(sources),
        "top_similarity": top_similarity,
        "average_similarity": average_similarity
    })


retrieval_eval_df = pd.DataFrame(
    retrieval_results
)

retrieval_eval_df

Case-related chunks found: 2
Case-related chunks found: 2
Case-related chunks found: 2
Case-related chunks found: 2
Case-related chunks found: 2

,case,question,sources_retrieved,top_similarity,average_similarity
0,Kikiben Ors vs Balvantlal Shivlal,What was the final decision of the court?,2,0.584620,0.512183
1,Kikiben Ors vs Balvantlal Shivlal,What was the main legal issue in this case?,2,0.420693,0.394241
2,Kikiben Ors vs Balvantlal Shivlal,What did the court decide regarding the appeals?,2,0.640997,0.572465
3,Kikiben Ors vs Balvantlal Shivlal,What happened to the suits filed by the respon...,2,0.543400,0.457179
4,Kikiben Ors vs Balvantlal Shivlal,Did the court award any costs?,2,0.525217,0.439615

In [75]:
print(
    "Average Top Similarity:",
    round(
        retrieval_eval_df["top_similarity"].mean(),
        4
    )
)

print(
    "Average Similarity:",
    round(
        retrieval_eval_df["average_similarity"].mean(),
        4
    )
)

print(
    "Average Sources Retrieved:",
    round(
        retrieval_eval_df["sources_retrieved"].mean(),
        2
    )
)

Average Top Similarity: 0.543
Average Similarity: 0.4751
Average Sources Retrieved: 2.0

In [76]:
retrieval_eval_df.to_csv(
    "retrieval_only_evaluation.csv",
    index=False
)

print("Retrieval evaluation saved successfully.")

Retrieval evaluation saved successfully.

In [78]:

# VERIFY FINAL RAG ARTIFACTS


import os

required_files = [
    "rag_artifacts/legal_judgment_faiss.index",
    "rag_artifacts/legal_judgment_chunks.pkl",
    "retrieval_only_evaluation.csv"
]

print("Checking required files...\n")

for file_path in required_files:

    if os.path.exists(file_path):

        size_mb = os.path.getsize(file_path) / (1024 * 1024)

        print(f"✅ {file_path}")
        print(f"   Size: {size_mb:.2f} MB")

    else:

        print(f"❌ Missing: {file_path}")

Checking required files...

✅ rag_artifacts/legal_judgment_faiss.index
   Size: 78.75 MB
✅ rag_artifacts/legal_judgment_chunks.pkl
   Size: 201.75 MB
✅ retrieval_only_evaluation.csv
   Size: 0.00 MB

# Deployment files prepare

In [79]:

# CREATE DEPLOYMENT PACKAGE

import os
import shutil

deployment_folder = "legal_rag_deployment"

os.makedirs(
    deployment_folder,
    exist_ok=True
)

# Copy FAISS index
shutil.copy2(
    "rag_artifacts/legal_judgment_faiss.index",
    f"{deployment_folder}/legal_judgment_faiss.index"
)

# Copy chunk metadata
shutil.copy2(
    "rag_artifacts/legal_judgment_chunks.pkl",
    f"{deployment_folder}/legal_judgment_chunks.pkl"
)

print("Deployment files created successfully.")

print("\nFiles:")

for file in os.listdir(deployment_folder):

    path = os.path.join(
        deployment_folder,
        file
    )

    size_mb = os.path.getsize(path) / (1024 * 1024)

    print(
        f"{file} → {size_mb:.2f} MB"
    )

Deployment files created successfully.

Files:
legal_judgment_faiss.index → 78.75 MB
legal_judgment_chunks.pkl → 201.75 MB